### ISSUE TITLE
[PLUGIN] Keep Google Icons Up to date

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#10]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 14:17 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/461_

----

## Feature description

I want access to the latest Google Icons.

Resources: https://developers.google.com/fonts/docs/developer_api
Related to #354
This ticket was split from #383 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Icons should be able to be auto-updated (interval or auto-detection on when an update is available?)
2. Add an option to opt-out of auto-updates 
3. A plugin update is not required to receive Icon updates
4. Performance should be kept in mind (e.g. use caching, not cron job, look at how PWAs work)

## Implementation brief

* Updates should happen when the Selector comes into focus in the Customizer
* An update constitutes checking a transient in the database. If an install has an object cache, core behavior stores transients as cached items and reduces reads on MySQL.
* A transient should have a 24h expiry to avoid overloading the Fonts API
* If a transient exists, bail and let existing behavior read from local stored JSON file in `assets/fonts/icons.codepoints`.
* If transient does not exist, or is expired, request new list from the Github Repo. `https://raw.githubusercontent.com/google/material-design-icons/master/font/MaterialIcons-Regular.codepoints`
* For consistency and compatibility with npm.grunt, this file should be saved to `assets/fonts/icons.codepoint`
* Subsequentally, the contents of this file needs to be split on linebreaks. PHP `file()` function does this.
* The resulting array can be used to write to `assets/fonts/icons.json`. 
* Each line is formatted as `name code` and should be split again on a space to create a JSON object such as:

```
{
  "icons": {
    "e577": {
      "name": "360"
    },
    "e84d": {
        "name": "3d_rotation"
    }
}
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 17:12 GMT_

----

After the IB is written, please assign to Rody to review

**Comment by ravichdev** [comment]
<a href="https://github.com/ravichdev"><img src="https://avatars.githubusercontent.com/u/26096061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravichdev](https://github.com/ravichdev)**
_Friday Dec 11, 2020 at 17:06 GMT_

----

Currently `codepoints` file is manually added to this repo and we have a [grunt command](https://github.com/xwp/material-design-wp-plugin/blob/develop/Gruntfile.js#L119-L139) which transforms the `codepoints` file to a JS understandable JSON file. TO enable auto-updates we have to look for a solution in PHP to download the latest `codepoints` file and transform that into the JSON file in PHP.

**Comment by ravichdev** [comment]
<a href="https://github.com/technosailor"><img src="https://avatars.githubusercontent.com/u/725303?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [technosailor](https://github.com/technosailor)**
_Tuesday Dec 15, 2020 at 16:14 GMT_

----

Hi @rodydavis-

I failed to assign this to you yesterday. So now I have.

Please review the updated implementation brief. 

Thanks!

**Comment by ravichdev** [comment]
<a href="https://github.com/rodydavis"><img src="https://avatars.githubusercontent.com/u/31253215?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodydavis](https://github.com/rodydavis)**
_Thursday Dec 17, 2020 at 16:38 GMT_

----

Looks great to me! This caching strategy will help a lot. We could probably increase the transient to 24h expiry since the fonts will not change that much. 

If someone is working on websites all day it would trigger 8 calls in a work day potentially and if they had multiple sites to manage 1 user could trigger up to 8 per site per hour. Ideally we want 1 per site per day.

**Comment by ravichdev** [comment]
<a href="https://github.com/rodydavis"><img src="https://avatars.githubusercontent.com/u/31253215?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodydavis](https://github.com/rodydavis)**
_Thursday Dec 17, 2020 at 16:42 GMT_

----

If they opt out of auto-updates will there be an button to refresh in settings?

If we do have a button it should still follow the same strategy where it will only call the api 1 per day. We could add messaging "Icons update every 24 hours" or something like that.

**Comment by ravichdev** [comment]
<a href="https://github.com/technosailor"><img src="https://avatars.githubusercontent.com/u/725303?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [technosailor](https://github.com/technosailor)**
_Thursday Dec 17, 2020 at 16:51 GMT_

----

The expiry change makes sense, @rodydavis. I'll update the IB with that.

I sorta see the opt-in portion of both fonts and icons as being a part of https://github.com/xwp/material-design-wp-plugin/issues/380. Maybe that makes that ticket take precedence over https://github.com/xwp/material-design-wp-plugin/issues/460 and https://github.com/xwp/material-design-wp-plugin/issues/461, but fundamentally I think they deal with different mechanisms. Do you have thoughts on this?

**Comment by ravichdev** [comment]
<a href="https://github.com/rodydavis"><img src="https://avatars.githubusercontent.com/u/31253215?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodydavis](https://github.com/rodydavis)**
_Thursday Dec 17, 2020 at 17:07 GMT_

----

Sounds good. I think we could even have a single button in the settings that will "Update fonts and icons" and maybe another one that will only be for debugging "Reset Cache" but the latter will be for all cache issues

**Comment by csossi** [comment]
verified in QA
