### ISSUE TITLE
[Pattern] Single Feature

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#100]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115761162-0aee8300-a370-11eb-995e-182b19174d68.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
