### ISSUE TITLE
[Pattern] Single Feature Extended

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#101]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115761246-222d7080-a370-11eb-94d5-063245b2786d.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
