### ISSUE TITLE
[Pattern] Highlights

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#103]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. I am able to add the Highlights Pattern
2. It should resemble the mockup attached
3. After adding the pattern it should have all blocks added to the post/page with demo material including:
   1. 3 column layout including:
   2. Column 1:
      1. Heading Block
      2. Paragraph Block
      3. Button Block
   3. Columns 2 and 3:
      1. Icon Block
      2. Heading Block
      3. Paragraph Block
      4. Spacer
      4. Icon Block
      2. Heading Block
      3. Paragraph Block

![image](https://user-images.githubusercontent.com/5874851/115761420-50ab4b80-a370-11eb-9f1e-0b2749ff3d3e.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Assuming here that this shouldn't default to having this line break on "Highlights":
![image](https://user-images.githubusercontent.com/16945664/117062454-73831b80-acf1-11eb-9118-d8b1e1cf48ea.png)

**Comment by csossi** [comment]
Verified in QA
