### ISSUE TITLE
[Pattern] Media Grid

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#104]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115761750-b0095b80-a370-11eb-9ed6-25905986e4b3.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
