### ISSUE TITLE
[Pattern] Contact Form

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#105]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115761892-d4fdce80-a370-11eb-9a4a-7fba3d27c228.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Message field was set to "required":
![image](https://user-images.githubusercontent.com/16945664/116817998-12afe380-ab37-11eb-8c3e-966412f6ec6d.png)

But when I tested on fron-end, was able to send with just email address and name. Left Message section blank and got the "thanks" display:
![image](https://user-images.githubusercontent.com/16945664/116818023-3d01a100-ab37-11eb-8614-635b0caaf77d.png)

**Comment by csossi** [comment]
Verified in QA
