### ISSUE TITLE
Icon Block

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#107]
## Feature description

As a site editor I want to add an icon block 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. THere are preset options (small, medium, large, xl, custom)
   2. When custom is selected a slider is presented to the user
2. Users are only able to add the icon for disiply (ie no tooltip or link, to do this they will need to use an icon button)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
