### ISSUE TITLE
Curated Post Block: Improve Post List Display

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#11]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Thursday Dec 10, 2020 at 19:25 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/470_

----

## Feature description

As an editor, I want a way to preview posts so that I can add the correct ones to my curated cards collection block. 

Improve how posts are displayed when they have no title.

Current state:
![image](https://user-images.githubusercontent.com/5874851/101819457-4a1fe400-3af3-11eb-8c18-8196c30db5c7.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. In situations where Curated Posts (AKA hand-picked posts) show up with no title, show: `(no title)`
2. Clicking on the "preview" pill will open the post/page in a new tab
3. Fix rounded corners: https://d.pr/i/6hC3tF. The pill showing selected posts should encompass the full title

Design to implement:
![image](https://user-images.githubusercontent.com/5874851/109180577-03887000-7759-11eb-9cb8-85c4f2d7c055.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Thursday Dec 10, 2020 at 19:26 GMT_

----

- ~Note: We should examine a UI to try and pull from pages or posts, but not go forward unless we’re confident that its an improvement over the existing state. That UI could show a large list, where posts and pages are shown together, and users can cross select. Worth exploring and seeing if we want to proceed.~ covered by #66
- ~Fix rounded corners: https://d.pr/i/6hC3tF.~ covered in AC above
- ~Two ideas: Have a icon to open the post in a new tab, that way you can preview it; or try having the additional next lines of post display in the preview. (Note: Also take a look at Woo, how handled the ID showing)~ going to try linkable ID instead of icon.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Wednesday Dec 16, 2020 at 18:58 GMT_

----

Hey @jwold I think this needs your input on what the outcome should be.

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Thursday Jan 14, 2021 at 20:33 GMT_

----

<img width="1077" alt="Screen Shot 2021-01-14 at 12 33 05 PM" src="https://user-images.githubusercontent.com/3411173/104645995-b5198900-5664-11eb-86b7-b6604e00252a.png">

Settled on two approaches we could take for this. Feedback is welcome.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Jan 15, 2021 at 16:07 GMT_

----

@ravichdev to investigate if these options are viable.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Jan 15, 2021 at 16:07 GMT_

----

@jwold can you please add a new option C where on the right hand side it will simply say "open" or "preview" or something to that effect. Thanks!

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Friday Jan 15, 2021 at 21:34 GMT_

----

Updated:

<img width="1508" alt="Screen Shot 2021-01-15 at 1 33 47 PM" src="https://user-images.githubusercontent.com/3411173/104780875-53c1ea80-5736-11eb-8c33-f5e836510537.png">

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 05, 2021 at 16:54 GMT_

----

Need to review options during grooming with the team

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 05, 2021 at 18:25 GMT_

----

@rodydavis when we last discussed this, we wanted to see option C that Joshua provided above. Do you want to discuss in our next grooming or do you want to pick one of the options and move this ticket in "To Do"?

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 12, 2021 at 16:25 GMT_

----

@dawidmlynarz to review option C above. If there are no other changes to discuss, unassign yourself and then an engineer can being working on this.

@jauyong to update AC

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Friday Feb 19, 2021 at 12:49 GMT_

----

@jauyong I have reviewed Option C and we can go with this as it is proposed by Joshua. Looks good to me!

**Comment by ravichdev** [comment]
<a href="https://github.com/rodydavis"><img src="https://avatars.githubusercontent.com/u/31253215?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodydavis](https://github.com/rodydavis)**
_Friday Feb 19, 2021 at 16:29 GMT_

----

LGTM

Rody Davis

**Comment by csossi** [comment]
"(no title)" isn't appearing:

![image](https://user-images.githubusercontent.com/16945664/114442851-fefa0880-9b9a-11eb-93d5-d5bce0822d36.png)

**Comment by ravichdev** [comment]
@csossi This is updated and ready for your review on staging

**Comment by csossi** [comment]
Verified in QA
