### ISSUE TITLE
Material color palette not working

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#116]
## Bug Description
Material Color palette not showing on click in Gutenberg editor.

Props to @ravichdev for finding this issue.

## Expected Behaviour
Color palette should show colors in Gutenberg editor on click of `Color palette` link.

## Steps to reproduce

1. Add a button. 
1. Go to color and background color. 
1. Click `color palette`. 

## Screenshots

https://user-images.githubusercontent.com/5015489/116686016-db272700-a9d0-11eb-80b9-77e71a1612dc.mp4

## Additional context

 - WordPress version: 5.7
 - Plugin version: 0.2
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/119342436-141a8a80-bc63-11eb-8a30-54a38cb4e2f7.png)
