### ISSUE TITLE
Improve Gallery (grid view) on Mobile

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#12]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Tuesday Jan 05, 2021 at 16:31 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/491_

----

## Feature description

As a user, I would like an improved experience for the gallery block on a mobile device.

This came from Yasmine's request regarding to the grid view for the Gallery block on mobile. See [slack message here](https://xwp.slack.com/archives/CSS5LFZJB/p1609861118055800).
![image](https://user-images.githubusercontent.com/5874851/104747287-56b0e100-571e-11eb-9aa4-12f413aec6c0.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. ~Conduct quick competitive analysis of similar blocks in the WordPress space to identify the best method for showcasing gallery blocks and giving content creators the best controls to modify the experience.~ Reviewed by Joshua.
2. ~The labels do not need to be cut off but break on the word (ie multiple lines)~ See #497 
3. Allow admins to set number of columns per device (desktop, tablet, mobile). The following are the defaults:
    1. desktop = 5 or 6, 
    2. tablet (768px) = 3 or 4, 
    3. mobile = 1
4. On mobile, I should be able to set 1 column

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Thursday Jan 14, 2021 at 20:46 GMT_

----

@jauyong I can't remember if there was anything needed from me on this one. I think we're ready for engineering.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Jan 15, 2021 at 16:12 GMT_

----

@jwold we were thinking of having default columns for each device type. what are your thoughts?
(desktop = 5 or 6, tablet (768px) = 3 or 4, mobile  = 1)

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Jan 15, 2021 at 16:12 GMT_

----

@jauyong to break this out into a separate ticket:
AC2 
The labels do not need to be cut off but break on the word (ie multiple lines)

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Friday Jan 15, 2021 at 19:57 GMT_

----

> @jwold we were thinking of having default columns for each device type. what are your thoughts?
(desktop = 5 or 6, tablet (768px) = 3 or 4, mobile = 1)

That works.

**Comment by ravichdev** [comment]
<a href="https://github.com/ravichdev"><img src="https://avatars.githubusercontent.com/u/26096061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravichdev](https://github.com/ravichdev)**
_Monday Mar 22, 2021 at 10:50 GMT_

----

@csossi This is ready for QA

**Comment by csossi** [comment]
@ravichdev 

- Added a new post. Added Gallery Block. Desktop defaulted to 4 columns - expected 5 or 6 as per AC above
![image](https://user-images.githubusercontent.com/16945664/113580695-11e96780-95f4-11eb-8a69-68e9ef15b490.png)

- should there be a tooltip when user hovers over the desktop, tablet, and mobile icons?

**Comment by ravichdev** [comment]
@csossi I've updated the default desktop columns to 5 and also added tooltips for the device icons. This is ready for QA.

**Comment by csossi** [comment]
Verified in QA
