### ISSUE TITLE
Add Tags on WordPress.org 

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#125]
## Feature description

As Material, I want the plugin to be as highly discoverable as possible. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Add tags to the plugin listing 
   1. Material design
   2. Material theming
   3. Google
   4. blocks
   5. Gutenberg
   6. Theme builder 
   7. Accessibility
   8. Dark Mode
2. Add tags to the theme listing 
   1. block-patterns
   2. blog
   3. grid-layout
   4. accessibility-ready
   5. theme-options
   

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
For reference: https://thriveagency.com/news/optimization-strategies-for-the-wordpress-plugin-directory/

**Comment by PatelUtkarsh** [comment]
Additional: Needs dark mode specific tags. @jauyong

**Comment by PatelUtkarsh** [comment]
@jauyong Our current theme tags: 
```Tags: blog, custom-colors, custom-logo, custom-menu, featured-images, full-width-template, one-column, threaded-comments, accessibility-ready, footer-widgets, editor-style, sticky-post, translation-ready, rtl-language-support, block-styles, wide-blocks```

Plugin has none.

**Comment by PatelUtkarsh** [comment]
@jauyong For theme, Do we want to add in addition to existing  tag or replace?

**Comment by PatelUtkarsh** [comment]
Comparing to the list, we can add `block-patterns` tag in theme and add new tags in plugin as specified in ticket description.
