### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#13]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Thursday Feb 04, 2021 at 20:37 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/534_

----

## Feature description

As a plugin user, I want to be able to manage my settings such as updating fonts and icons

This is a blocker to #460 and #461

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Add a new settings page under the "Getting Started" tabs
2. Add option for manual icon update
3. Add option for manual font update
4. #537 ~Add option to delete cache, reset demo content, hard reset theme... @jauyong to create a ticket for this. need to identify what can be reset. This ticket will help users troubleshoot and get back to a stable default state.~ 
5. Add any settings that affect the backend (ie settings that don't belong in the customizer)
6. Add API Key field
7. When the API key is entered and the user refreshes/returns to the page, the key should be hidden (like how passwords are treated) or consider removing the text field altogether. Also look at Github secrets.
8. Clicking on "activate Google API Key" first brings you down to the input field on the page. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Thursday Feb 04, 2021 at 20:38 GMT_

----

@jwold do I recall correctly that you wanted to take a look at this first?

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 05, 2021 at 17:44 GMT_

----

@jwold Aaron just confirmed that you wanted to look at this first to provide a design, so passing it on to you. 

There were comments to mirror the existing "getting started" look and feel, but I'm sure you'll work out what's best ;)

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Wednesday Feb 10, 2021 at 15:24 GMT_

----

Reassigning to @dawidmlynarz to take a look

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Friday Feb 12, 2021 at 10:50 GMT_

----

Hey @jauyong , here is my first draft and a quick prototype of the Settings page. I tried to keep the same styles from the 'Getting Started' page to keep consistency.

The first section of the page is `Resources` but if you have a better name please let me know. It consists of Google Fonts and Material Icons tiles with the ability to Update them manually or turn on auto-updates. That's something I discussed with @ravichdev but I'd love to get the technical feedback again as well.

Things I've additionally included into the concept:
- Settings tab in the left side menu with a notification when the new updates appear.
- Last update date to have more context when the user comes to the page.

Take a look at the quick prototype recording and let me know your thoughts.

https://user-images.githubusercontent.com/8026823/107759317-6b39c680-6d28-11eb-9587-a89bcb3368ca.mov

Looking forward to your feedback!

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Monday Feb 15, 2021 at 13:08 GMT_

----

Please have a look at the revisited version of the Settings page. The following changes were made:
• Settings page is now below Getting started on sidebar
• Resources section name was changed into Integrations
• Created new section for Google API Key
• Included ability to Edit / Delete activated Google API Key
• Presented how Google API Key dependency could work with Integrations

https://user-images.githubusercontent.com/8026823/107950063-7f82fb00-6f96-11eb-951f-2f068beb64a2.mov

Looking forward to more feedback on this.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 19, 2021 at 17:53 GMT_

----

When the API key is entered, and the user returns to the page, the key should be hidden like a password is. Or consider removing the text field altogether. (look at Github secrets)

Jason to update AC and reference the ticket to reset settings.

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Wednesday Feb 24, 2021 at 13:24 GMT_

----

@jauyong Here is the proposal of how can we handle the 'hidden state'. We can display it again once someone wants to edit it. The question to consider is: **Should this access be password protected?**

![Settings – Google Fonts – Hidden API](https://user-images.githubusercontent.com/8026823/109007089-0c6f3800-76ac-11eb-9d82-362b5aa050c8.png)

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Thursday Feb 25, 2021 at 15:46 GMT_

----

@dawidmlynarz good question. Password protection wasn't mentioned when we were discussing this. I feel like that could cause more headaches for us and the user through complexities like password management. We can ask the team though.

I also remember it being mentioned that users shouldn't be able to edit the keys, but only remove them. I don't see any notes here and that your approved video demo shows an edit button. 

@rodydavis can you confirm:
1. Users can only delete a saved API key, not edit.
2. Is there any need for password protecting the API key?

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 26, 2021 at 16:05 GMT_

----

@dawidmlynarz to make the following update:
1. remove the edit button. 

no need for password protection.

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Monday Mar 01, 2021 at 09:50 GMT_

----

Please find updated screens of Google API Key interaction below divided into states:

### Empty state
![Settings – Google API Key](https://user-images.githubusercontent.com/8026823/109480168-7f492c00-7a7b-11eb-8936-4fe133eff5b3.png)

### Active / Typing KEY
![Settings – Google API Key – Typing](https://user-images.githubusercontent.com/8026823/109480187-853f0d00-7a7b-11eb-991c-f29990a1c373.png)

### API Key Activated
![Settings – Google API Key – Active](https://user-images.githubusercontent.com/8026823/109480238-96881980-7a7b-11eb-9d14-5ead9525d277.png)

### API Key Hidden
![Settings – Google Fonts – Hidden API](https://user-images.githubusercontent.com/8026823/109480320-ac95da00-7a7b-11eb-8502-e7f22c392344.png)

### API Key Remove Confirmation
<img width="1150" alt="Settings – Google API Key – Remove Confirmation" src="https://user-images.githubusercontent.com/8026823/109480369-bae3f600-7a7b-11eb-8c4b-dc0ba0d36f06.png">

**NOTE:** Let me know when you're taking the task and I can provide you a link to Figma.

**Comment by ravichdev** [comment]
<a href="https://github.com/ravichdev"><img src="https://avatars.githubusercontent.com/u/26096061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravichdev](https://github.com/ravichdev)**
_Monday Mar 01, 2021 at 10:00 GMT_

----

@dawidmlynarz Looks good, for the API key field, after a user enters the key and saves it, they wouldn't be able to see it. It will be `***` like a password field. We are good here though, don't think we need to update the mocks to denote the password field update.

**Comment by ravichdev** [comment]
<a href="https://github.com/emeaguiar"><img src="https://avatars.githubusercontent.com/u/1379732?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emeaguiar](https://github.com/emeaguiar)**
_Monday Mar 08, 2021 at 19:11 GMT_

----

@dawidmlynarz Would you happen to have either the figma link or a sketch file with these updates? Wondering if I can get the color values or there more specifics that I can't get in the videos

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Wednesday Mar 10, 2021 at 09:36 GMT_

----

@emeaguiar I have sent you Figma link via Slack. Let me know if you have access.

**Comment by csossi** [comment]
Verified in QA
