### ISSUE TITLE
remove Page title in front page

### ISSUE THREAD

**Issue by kevinkovadia** [material-components/material-design-for-wordpress#137]
## Bug Description

when i keep the home page as front page, that front page also show page title "home", which need to remvoed.
i am using WordPress 5.7.2, material design google WordPress theme and plugin for the same. kindly have a look at the screenshot for better understanding
![Screenshot (38)](https://user-images.githubusercontent.com/38972017/120167952-f7122880-c21b-11eb-9cb3-94f43e3a7320.png)
.

**Comment by PatelUtkarsh** [comment]
Hello @kevinkovadia, thank you for reaching out. 

We are working on #83 which will allow hiding page title for a given page.
