### ISSUE TITLE
[FSE] Replicate Default Settings

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#139]
## Feature description

Replicate the current default settings for full site editing. When you enable FSE, it disables the customizer so we need to bring it back. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. The following values in the customizer are ported to the full site editing panel
   1. Material Design Options
      1. Style
      2. Colour Pallete
      3. Typography
      4. Shape Size
      5. Icon Styles
      6. Top app bar & Footer
 2. For version 1 with backwards compatibility, we will keep the customizer and have the settings in both sections. Once we drop backwards compatibility we will only have it ported in the FSE settings
   2. https://github.com/WordPress/theme-experiments/blob/master/tt1-blocks/theme.json

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
For the first release of FSE, we'll keep the customizer and make sure it is enabled when FSE is turned on. Later we'll determine how to port over features to the FSE editor panel.

**Comment by igruszkauy** [comment]
Closing as it's not needed.

**Comment by PatelUtkarsh** [comment]
We can reopen when we want to move color settings from customizer to FSE.
