### ISSUE TITLE
[FSE] Add additional CSS classes / global style

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#147]
## Feature description

Configure theme.JSON
Add addition CSS classes required for full site editing

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Full site editing settings cascade into blocks
2. Configure theme.JSON to support FSE

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
We can potentially add m2 fonts in theme.json, we are doing that as part of m3 which may eventually end up in fse. #352
