### ISSUE TITLE
Fix Sort Order of Posts on Mobile for Masonry Layout

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#15]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Monday Feb 22, 2021 at 19:43 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/549_

----

## Bug Description

Original Ticket: https://wordpress.org/support/topic/sort-order-of-last-posts-on-homepage/

In the masonry layout in the theme, the columns are two divs which hold all the posts and this changes the sort order for mobile

Note: Verify that this does not occur on the card blocks in the plugin

## Expected Behaviour

On mobile, the order the posts are displayed in should be "correct" and match the order displayed on larger screen displays.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. On mobile, the order the posts are displayed in should be "correct" and match the order displayed on larger screen displays.
2. Verify that this does not occur on the card blocks in the plugin

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 26, 2021 at 16:32 GMT_

----

@rodydavis  to add ways to do this with modern CSS

**Comment by ravichdev** [comment]
<a href="https://github.com/emeaguiar"><img src="https://avatars.githubusercontent.com/u/1379732?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emeaguiar](https://github.com/emeaguiar)**
_Friday Mar 05, 2021 at 17:44 GMT_

----


see [https://www.smashingmagazine.com/native-css-masonry-layout-css-grid/](https://www.smashingmagazine.com/native-css-masonry-layout-css-grid/)

**Comment by ravichdev** [comment]
<a href="https://github.com/emeaguiar"><img src="https://avatars.githubusercontent.com/u/1379732?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emeaguiar](https://github.com/emeaguiar)**
_Monday Mar 15, 2021 at 18:02 GMT_

----

Note that solution in https://github.com/xwp/material-design-wp-plugin/issues/549#issuecomment-791577056 is no longer valid as it only worked in Firefox and needs to be activated by the user

**Comment by csossi** [comment]
@PatelUtkarsh - I just want to verify the expectation re: Curated Card Collection. In desktop, cards are presented in this order on my test page:
![image](https://user-images.githubusercontent.com/16945664/125213288-cc39dc00-e27f-11eb-9221-c512025a996f.png)

In mobile, the order is vertical:
![image](https://user-images.githubusercontent.com/16945664/125213329-f4c1d600-e27f-11eb-99a7-76dd6c2a6f49.png)
![image](https://user-images.githubusercontent.com/16945664/125213351-0c995a00-e280-11eb-924a-0310feca4440.png)
![image](https://user-images.githubusercontent.com/16945664/125213367-25097480-e280-11eb-81d3-855e5248560a.png)

Is this the expectation here, or should curated cards be ordered "across"?

**Comment by PatelUtkarsh** [comment]
@emeaguiar Can you take this one?

**Comment by emeaguiar** [comment]
Hey @csossi , this update applies only to the theme, here are the testing instructions:

1. Go to https://dev-mdc-web.pantheonsite.io/blog/
2. Note the order of posts from left to right, for example:
![Desktop](https://p200.p0.n0.cdn.getcloudapp.com/items/qGu5GY4n/7c982cee-a525-4ead-9e47-8ca542eb0f53.png?v=a9795f2df7fcd7950335e82ac4103c9a)
3. Resize to mobile view, and **reload the page**
4. Scroll down and ensure posts order remains the same, for example:
![Mobile](https://p200.p0.n0.cdn.getcloudapp.com/items/yAurqnd6/81ee7fc7-522f-4072-9150-237270cca14f.png?v=a28826b47a92697ec2465194cd66515c)
5. Go to customizer: https://dev-mdc-web.pantheonsite.io/wp-admin/customize.php?url=https%3A%2F%2Fdev-mdc-web.pantheonsite.io%2Fblog%2F (or click customizer in the admin bar)
6. Navigate to Material Design Options -> Post Settings (https://share.getcloudapp.com/jkuPk8Em)
7. Switch "Posts layout width" from "Wide" to "Normal" and vice versa
8. Switch "Posts layout" from "Card" to "Image list"
9. Ensure **Card** layout retains order from left to right (https://share.getcloudapp.com/WnuxnX9z)

**Comment by csossi** [comment]
Verified in QA

@emeaguiar - thank you for the detailed QA instructions!

**Comment by jauyong** [comment]
@jauyong to add demo of the fix

**Comment by jauyong** [comment]
I thought a screenshot with a side by side comparison of desktop vs mobile would better capture a demo of the fix:
![Group 1 (1)](https://user-images.githubusercontent.com/5874851/136397568-69d72473-0fbe-4dbb-82c5-05eef4ab1566.png)
