### ISSUE TITLE
Route Bug on WP.org

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#158]
## Bug Description

![image](https://user-images.githubusercontent.com/5874851/121549740-1f4c1500-c9dc-11eb-9040-33eb6175b05e.png)

Works when theme is disabled:
![image](https://user-images.githubusercontent.com/5874851/121549779-283ce680-c9dc-11eb-9001-e97fff95045a.png)

There is one particular route: wp-json/material-design/v1/onboarding/retrieve-icons/force which is going 404.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

1. ensure that the error message shown in the image above does not appear

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
