### ISSUE TITLE
[Discovery] Color Logic

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#159]
## Feature description

Research colour logic required for dark mode and high-contrast mode. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. A solution for calculating colour options is decided on

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbearne** [comment]
possible helper js for the switching 
https://github.com/GoogleChromeLabs/dark-mode-toggle
https://medium.com/@haxzie/dark-and-light-theme-switcher-using-css-variables-and-pure-javascript-zocada-dd0059d72fa2
https://github.com/Fcmam5/nightly.js

https://github.com/itsabdessalam/is-night-mode

**Comment by pbearne** [comment]
Contrast code
https://dev.to/alvaromontoro/building-your-own-color-contrast-checker-4j7o

https://gist.github.com/dcondrey/183971f17808e9277572

**Comment by pbearne** [comment]
Lib to switch mode has nice animations
https://github.com/sandoche/Darkmode.js/blob/master/src/darkmode.js

**Comment by pbearne** [comment]
how to calc contrast
https://stackoverflow.com/questions/9733288/how-to-programmatically-calculate-the-contrast-ratio-between-two-colors

How to change saturation
https://css-tricks.com/using-javascript-to-adjust-saturation-and-brightness-of-rgb-colors/

Changing the color space 
https://css-tricks.com/converting-color-spaces-in-javascript/
