### ISSUE TITLE
Can't remove image from card

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#16]
<a href="https://github.com/emeaguiar"><img src="https://avatars.githubusercontent.com/u/1379732?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emeaguiar](https://github.com/emeaguiar)**
_Monday Mar 15, 2021 at 17:36 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/564_

----

## Bug Description

The button to remove cards doesn't seem to work when clicked

## Expected Behaviour

Clicking the X button in cards images should remove the image from card and display the media selector again.

## Steps to reproduce

1. Go to edit post screen
2. Create a new card collection if needed
3. Add an image to any card
4. Hover over the top right corner of any card with an image, wait for the X button to appear
5. Click the button and confirm the image is NOT removed

## Screenshots

![Demo](https://share.getcloudapp.com/RBu4QBJJ)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: Firefox

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
