### ISSUE TITLE
[DM] Update Style Settings in Customizer

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#163]
## Feature description

With the addition of dark mode and high-contrast modes to the existing styles, we are updating how the settings in the customizer is laid out. 

[Figma Prototype](https://www.figma.com/proto/cNKMIkWy3I0YQBZ6GpSpNG/Google-%E2%80%93-MDC-Web?page-id=3131%3A0&node-id=3148%3A46182&viewport=160%2C-1367%2C0.7959950566291809&scaling=min-zoom)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Collapsed state should show style colors (square preview), active style, change button and preferences (settings) button
2. After clicking on the change button, the section should expand showing the start styles and custom style
   1. The starter styles should indicate if there is a dark mode version with an icon and with a hover label
   2. The starter styles should indicate if there is a high contrast mode version with an icon and with a hover label
1. After clicking the preferences (settings) button, I should see the options for dark mode and high contrast mode
## Implementation brief

![image](https://user-images.githubusercontent.com/5874851/122282897-f0d9a880-ceb9-11eb-817a-4c5760e42284.png)
![image](https://user-images.githubusercontent.com/5874851/122282913-f6cf8980-ceb9-11eb-914f-8ac78b43e388.png)
![image](https://user-images.githubusercontent.com/5874851/122282933-fd5e0100-ceb9-11eb-8d09-fbc1d121443c.png)

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by mattchungxwp** [comment]
Will need to update and add the front end user switch to enable Dark Mode/High Contrast

**Comment by PatelUtkarsh** [comment]
Testing instructions: Dark mode includes #163 and #164. 

High Contrast is currently out of scope, We are only focusing on dark mode:

Two users are involved: user who owns the website and changes color according to its preference let's call it admin, and end user who is viewing the website on the frontend let's call it end user.

1. Admin opens customizer ⇾ Material Design option ⇾ Color Palette.
1. Should see dark mode tab. It represents how that color should look when dark mode is activated. 
    <img width="292" alt="image" src="https://user-images.githubusercontent.com/5015489/131829710-9ede50cd-4978-40a5-9049-a2bde3ec7d04.png">
1. Link icon represent if color is auto calculated or not for dark mode from the base default color. If you're seeing unlink icon which means color is auto calculated, Ideally on change on dark mode color by using color picker or hash value it should unlink.
1. Opening setting gear shows how dark mode is enforced for the end user. 
    1. <img width="307" alt="image" src="https://user-images.githubusercontent.com/5015489/131830729-2185f875-0575-40b2-a198-c15ccab24dd2.png">
    2. <img width="304" alt="image" src="https://user-images.githubusercontent.com/5015489/131830781-c8494929-6b23-4959-aeda-f11bfaa6837f.png">
1. Display dark mode switcher should allow end user to switch between dark and light mode. (See right corner) Icon of dark / light mode should change accordingly and setting preference should be stored in browser.
    <img width="1252" alt="image" src="https://user-images.githubusercontent.com/5015489/131831016-c52fdd88-ef9c-4e2d-a91e-5955f7468e79.png">
1. Setting auto mode should take from system preference / browser preference. 
    1. In chrome, end user can open developer tools, Press cmd+p and type `> css color` and select emulate CSS `prefers-color-scheme: dark` or `prefers-color-scheme: light` to toggle.
    2. <img width="514" alt="image" src="https://user-images.githubusercontent.com/5015489/131831467-76d34d29-3b30-4cdc-9d11-10d11bdfd23f.png">
1. Setting dark mode active should default to dark mode and should allow user to pick light if switcher is on. 
1. For inactive, it should disable dark mode and switcher?
1. We should also test all material blocks with dark mode theme and see if they are looking acceptable and are taking dark colors from the theme.

**Comment by csossi** [comment]
@PatelUtkarsh , should this be working for Patterns as well? Light mode looks like this for Calls To Action:
![image](https://user-images.githubusercontent.com/16945664/132018085-dc9c6ca3-b0a5-4319-bedf-7d79f9e8d30a.png)
When I switch to dark mode, looks like this (hard to read):
![image](https://user-images.githubusercontent.com/16945664/132018285-008c4c5e-765e-438a-9377-fda97cfd6c75.png)

**Comment by csossi** [comment]
@PatelUtkarsh - some inconsistent behaviour when swithing within Settings. I have Dark Mode "active" here, with display witcher selected:
![image](https://user-images.githubusercontent.com/16945664/132018788-9722cf03-71a7-4ccd-8452-0b273b4c4b73.png)
Then I selected the switcher at top right and it switched to Light:
![image](https://user-images.githubusercontent.com/16945664/132018974-5feafe62-4a6a-4587-80ca-620ad8447ed6.png)
Then I selected switcher again to go back to Dark, but display wasn't the same as first image above:
![image](https://user-images.githubusercontent.com/16945664/132019148-eabdd77a-3949-48f2-bed7-553c7449c74e.png)

**Comment by PatelUtkarsh** [comment]
Calls To Action block may have white background, We can remove and update block. 

For point 2 @emeaguiar could you please take a look?

**Comment by emeaguiar** [comment]
@csossi I've updated issue 2


https://user-images.githubusercontent.com/1379732/132043891-3b65afaf-270c-424a-b819-7373bcd4f800.mp4

**Comment by jauyong** [comment]
@csossi the fixes for the background color and the CTA block are ready to test.
