### ISSUE TITLE
[DM] Update Color Palette Settings in Customizer

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#164]
## Feature description

With the addition of dark mode and high-contrast modes, we are updating how the settings in the customizer are laid out.

[Figma Prototype
](https://www.figma.com/proto/cNKMIkWy3I0YQBZ6GpSpNG/Google-%E2%80%93-MDC-Web?page-id=3131%3A0&node-id=3148%3A46186&viewport=160%2C-1367%2C0.7959950566291809&scaling=min-zoom)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. The color palette accordion should have the 4 tabs when applicable: Default, Dark Mode, High Contrast (Light), High Contrast (Dark)
2. After clicking on the dark mode tab, I should be able to edit the colors
3. After clicking on the dark mode tab, I should see a preview of dark mode
4. After clicking on the high contrast (light) mode tab, I should be able to edit the colors
5. After clicking on the high contrast (light) mode tab, I should see a preview of high contrast (light) mode
6. 4. After clicking on the high contrast (dark) mode tab, I should be able to edit the colors
7. After clicking on the high contrast (dark) mode tab, I should see a preview of high contrast (dark) mode
8. The user is able to unlink their darkmode/high contrast color selections for a "custom" setting
9. The user is able to link their dark mode/high contrast color selections so that they are "automatically" calculated based off of the default colour selection

![image](https://user-images.githubusercontent.com/5874851/122283485-9725ae00-ceba-11eb-9858-0f13d326ee51.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA (with the exception of contrast-related AC)
