### ISSUE TITLE
Utility Conversions

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#168]
## Feature description

Utility Classes required for Dark Mode. Given a colour, we should be able to identify the dark mode colour and font colour.

Note:
We currently have a color utility and Pau is adding to that

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Create a utility class interface (for existing functions)
   1.  Existing functions should be inheritied
   2. Add new functions to the class
2. Create a class to convert colour formats  
3. Create a class to calculate ratios between colours and set colours depending on ratios
4. If there is a dark colour and a dark font, the font should invert to a lighter colour
5. Add unit tests for all functions

## Implementation brief

* 

## QA testing instructions
- Test customizer with different color themes are working as expected. 
- In customizer, test custom theme has warning for color contrast.

Example: 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/5015489/128200538-29e14090-efac-4f39-a9b4-b323e6d48f24.png">

## Demo

* 

## Changelog entry

*

**Comment by claudiosossi** [comment]
Verified in QA
