### ISSUE TITLE
Image size on homepage

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#17]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Tuesday Mar 16, 2021 at 14:35 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/566_

----

## Bug Description

Original Ticket: https://wordpress.org/support/topic/image-size-on-homepage/

Note: this will happen for the plugin and the theme

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The image in the card layout is being set as a background-image (using css) to maintain the aspect ratio across all cards. Update it to use an `img` tag so WordPress can use `srcset` while also maintaining the aspect ratio.

## Implementation brief

* 

## QA testing instructions

* Card header image should use an `img` element.
* Existing card blocks should continue to work in the block editor and frontend.

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Not seeing the img element for card, @ravichdev . hear in card is showing as:
<div tabindex="0" class="mdc-card__media mdc-card__media--16-9 material-design-card__media material-design-card-with-text-under-media" style="background-image:url(https://dev-mdc-web.pantheonsite.io/wp-content/uploads/2021/04/cbCzHY9-1-1.gif)"></div>

**Comment by ravichdev** [comment]
@csossi If this is a card block, it needs to be edited in the block editor so it "converts" from the old version to the new version with the `img` element. Edit the page, make a small update to the block, save it and verify in frontend.

The "Blog" page which shows all blog posts (cards layout) should show the change without needing any edits.

**Comment by ravichdev** [comment]
@csossi I see the issue now, moving this back to "In Progress"

**Comment by ravichdev** [comment]
@csossi This is updated and ready for your review on staging.

An image in a card block will be updated after it's loaded in the block editor and any content in the post id edited and updated.

**Comment by csossi** [comment]
Verified in QA
