### ISSUE TITLE
Update Supported Versions - 5.6 +

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#179]
## Feature description

Now that 5.8 is out we need to update our officially supported versions. 

5.2 is now only getting maintenance/security support. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Update all official messaging to show support for 5.6+
   1. Put a notice in for this release and then actually remove support in the next release
   2. Declare supported versions in readme file 
2. Update Processing in Github
3. Remove unnecessary code for unsupported backwards compatibility
   1. Put a note on the upgrade notice regarding what was removed (5.4 support) 
4. Ship this as a hotfix, not a major release
5. Update GitHub action test suite to use WordPress 5.6 and up.

## Implementation brief

* 

## QA testing instructions

* this message only shows up if
* WP version is less than 5.6 (you can edit the version file to fake this)
* AND plugin version is 0.3.1 (you can set the plugin version to fake this)

## Demo

* 
* 
![image](https://user-images.githubusercontent.com/46270/127679433-da3c2bd4-d75c-40b3-9666-f8653a48bd24.png)

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
There are a couple of errors with WordPress 5.8 and material plugin - Error log from e2e is here: https://github.com/material-components/material-design-for-wordpress/pull/185/checks?check_run_id=3290635519#step:14:20

**Comment by PatelUtkarsh** [comment]
Following material blocks are failing with WP 5.8:
- Data table 
- Recent posts 
- Tab bar 
- List

**Comment by PatelUtkarsh** [comment]
> Update GitHub action test suite to use WordPress 5.6 and up.

This is done as part of https://github.com/material-components/material-design-for-wordpress/pull/185

**Comment by jauyong** [comment]
@jauyong to write copy

**Comment by jauyong** [comment]
Please note that the upcoming Material Theme/Plugin release ?0.3.2? will include updated support and will only support WordPress version 5.6 and up. 

CC: @PatelUtkarsh

**Comment by PatelUtkarsh** [comment]
@jauyong Since we don't know next to next release version yet, Should drop version number and keep it like following?

> Please note that the upcoming Material Theme and Plugin release will include updated support and will only support WordPress version 5.6 and up.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/5015489/130588567-c327bfd8-a8ac-4eb7-8191-cd3a30929f36.png">

The notice will be displayed only when next to next release is released on wp.org.

**Comment by PatelUtkarsh** [comment]
UI message will look different when WP is less than 5.8. Above screen shows message for 5.8, Below is for WP 5.7. 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/5015489/131796650-8515c6bf-2c91-4e63-9267-81f1ba94585c.png">
