### ISSUE TITLE
CLI Documentation

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#180]
## Feature description

Add documentation in the readme file for the CLIs

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. RE: #60 add a CLI related to the "reset" button in case there are large sites that can benefit from a CLI
2. Update documentation for all existing and the above new CLI

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbearne** [comment]
@jauyong can you look at the docs so far
https://github.com/material-components/material-design-for-wordpress/wiki

I feel we should ad some basic info the home page
Link to the contribute readme links to material.io and  WP.org etc.

**Comment by PatelUtkarsh** [comment]
Thank you, @pbearne! This looks good!
