### ISSUE TITLE
Material list: Post update button stays disabled on updating existing list item

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#199]
## Bug Description
https://user-images.githubusercontent.com/5015489/131834465-51f6e013-e6d8-4bfd-b27a-906ad0d7788b.mp4

## Expected Behaviour
1. On changing an existing material list item, update button should be enabled.

## Steps to reproduce
1. Create new post or open existing post with material list items. 
2. Without adding new list item change existing item. 
3. See update post button is disabled. 
4. Add new item - Update post button is enabled.

## Additional context

 - WordPress version: 5.8
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
