### ISSUE TITLE
Background Colour Issue with Preview

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#204]
## Bug Description

There is an issue with the preview of the website not showing updates to the background field. If you publish, it updates as expected so this is only an issue with preview as far as I can tell. 

Please see slack for video as the file is too large to post here. 

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
