### ISSUE TITLE
FSE - Search block 

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#226]
## Feature description

Search block for those other than the search in the header
See #234 

Could override default WP Core block markup for search, needed for 404

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Support all other search boxes outside of the header one in #234 (potentially the same)
   1. Inside Hamburger #235 
   2. On 404 Page

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by emeaguiar** [comment]
@PatelUtkarsh I just left a couple comments in the PR

**Comment by emeaguiar** [comment]
Approved PR

**Comment by PatelUtkarsh** [comment]
**Testing instruction:** 

1. Use new material search block.
1. This is used in 404 page #227 and search page.
2. To view search page, appending `/?s=test` to current site URL.

![image](https://user-images.githubusercontent.com/5015489/149112504-afde54d3-b95e-4fad-b9f2-b91471820889.png)

**Comment by igruszkauy** [comment]
- OK / Search block is displayed in 404 page
![image](https://user-images.githubusercontent.com/2902880/149504030-f055af18-f1e3-4f21-9192-2a72bba0caec.png)

- NOT OK / Search block is displayed in search page by default [/?s=test](https://fse-mdc-web.pantheonsite.io/?s=test)

- NOT OK/ User can add the Material Search Box to the Search page and it's reflected on the page
![image](https://user-images.githubusercontent.com/2902880/149505202-09fe580b-b686-4658-9c3a-99b06d2e4270.png)

![image](https://user-images.githubusercontent.com/2902880/149505249-f7a68335-59bb-4bc2-a27b-13351bb7bb23.png)

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, 

2. > NOT OK / Search block is displayed in search page by default /?s=test

We have removed search block from search page in favor of search query block. 

![image](https://user-images.githubusercontent.com/5015489/151318668-0b69379c-a704-41e1-9475-17e3c874bc89.png)


3. > NOT OK/ User can add the Material Search Box to the Search page and it's reflected on the page

This is being hidden due to menu coming down this is fixed, If you add search box in search page or 404 page it should be visible now.

**Comment by igruszkauy** [comment]
@PatelUtkarsh how can I configure the search page to display for empty results:
![image](https://user-images.githubusercontent.com/2902880/151960001-1ec15130-bbe5-4203-9173-321e90088039.png)
![image](https://user-images.githubusercontent.com/2902880/151960061-9a5fe93c-7bdc-42db-9d54-29b070bc2723.png)

**Comment by igruszkauy** [comment]
OK / Confirmed the search block can be added into the search template
![image](https://user-images.githubusercontent.com/2902880/151960385-42a9a1d6-c1bd-49e2-9a9a-2eb21dff30df.png)

OK / Confirmed the search query block is displayed by default in the search template
![image](https://user-images.githubusercontent.com/2902880/151960487-75694508-bdb8-4130-b35a-6c129a283583.png)

**Comment by felipebochehin87** [comment]
LGTM.
