### ISSUE TITLE
[FSE] Tab Block for Header Block

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#229]
## Feature description

Create a Tab Block to replicate the current header

![image](https://user-images.githubusercontent.com/5874851/140177718-b62492a6-ee1c-477c-b0aa-3cf53f606a70.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. User is able to manage Tabs

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by felipebochehin87** [comment]
@igruszkauy this looks good to me on the front end. I changed the menus, the look and feel, and this looks good to me.

**Comment by PatelUtkarsh** [comment]
@felipebochehin87 apart from minor bug with color on editor vs frontend nothing else is in progress.
