### ISSUE TITLE
[FSE] Dark Mode Switch Block for Header

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#232]
## Feature description

Create a Dark Mode Switch Block to replicate the current header

![image](https://user-images.githubusercontent.com/5874851/140177718-b62492a6-ee1c-477c-b0aa-3cf53f606a70.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. User is able to manage the Dark Mode Switch

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Testing instructions: 

1. User should be able to add / remove dark mode switch with FSE - should be available by default in header.
2. On click, it should change to dark mode color.

https://user-images.githubusercontent.com/5015489/149108986-a78f3cbf-2d86-4446-ba8d-37e3561f65a9.mp4

**Comment by igruszkauy** [comment]
Verified via https://fse-mdc-web.pantheonsite.io/wp-admin/site-editor.php?postType=wp_template_part&postId=material-design-google%2F%2Fheader

- OK / User can remove the Dark Mode Switch from the Header
![image](https://user-images.githubusercontent.com/2902880/149233229-8eb8da64-0376-4c56-b851-ec92524493c9.png)

- OK / User can re-add the Dark Mode Switch into the Header
![image](https://user-images.githubusercontent.com/2902880/149233341-6bc78f76-84c1-4d6c-b25e-6d5510e4a8bd.png)

**Comment by PatelUtkarsh** [comment]
Footer update is fixed https://github.com/material-components/material-design-for-wordpress/issues/278

**Comment by felipebochehin87** [comment]
LGTM.
