### ISSUE TITLE
[FSE] Logo Block for Header

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#233]
## Feature description

Create a Logo Block (outside hamburger drawer) to replicate the current header

![image](https://user-images.githubusercontent.com/5874851/140177718-b62492a6-ee1c-477c-b0aa-3cf53f606a70.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. User is able to manage the Logo (outside hamburger drawer)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by igruszkauy** [comment]
Verified via https://fse-mdc-web.pantheonsite.io/wp-admin/site-editor.php?postType=wp_template_part&postId=material-design-google%2F%2Fheader

- OK / User can remove the Site Logo block from the Header
![image](https://user-images.githubusercontent.com/2902880/149332360-4ade4e68-ca87-40a2-9550-d6a0dafea553.png)
![image](https://user-images.githubusercontent.com/2902880/149332496-4d31b4d1-f694-4441-829e-2942d12b71ca.png)

- OK / User can search and select the Site Logo block from the Header
![image](https://user-images.githubusercontent.com/2902880/149332683-517f73ff-316e-4930-8198-11b6ef6c66df.png)

- NOT OK / After adding the Site Logo block and saving, the logo is displayed in an incorrect position. When going back to the editor the block is being automatically removed from the header where it was placed
https://user-images.githubusercontent.com/2902880/149333844-69217f76-049f-4cf7-8944-b5e76cef5a2e.mp4

**Comment by emeaguiar** [comment]
It seems like the logo not taking to the max size was the issue, I have added the missing styles, we will need to find a way to inject the styles into the editor so we get the same experience there cc @PatelUtkarsh 

https://user-images.githubusercontent.com/1379732/151289416-d1e35456-0ec3-4caa-8eb4-e968af8b91e2.mp4

**Comment by igruszkauy** [comment]
OK / After adding the Site Logo block and saving, the logo is displayed correctly
![image](https://user-images.githubusercontent.com/2902880/151962084-fce4ce20-f361-4775-9557-adb3b8b7ea5e.png)

**Comment by felipebochehin87** [comment]
LGTM.
