### ISSUE TITLE
[FSE] Search Block for Header

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#234]
## Feature description

Create a Search Block (outside hamburger drawer) to replicate the current header

![image](https://user-images.githubusercontent.com/5874851/140177718-b62492a6-ee1c-477c-b0aa-3cf53f606a70.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. User is able to manage the Search Box (outside hamburger drawer)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
@felipebochehin87 You can see demo in https://github.com/material-components/material-design-for-wordpress/pull/311

**Comment by felipebochehin87** [comment]
@PatelUtkarsh the functionality looks good, but I noticed a layout issue on both Firefox, Safari and Chrome.

1. Click on the magnifying glass
2. Search for "test" - see that the "Search Results for: test" are slightly covered be the upper banner

The video below is showing Chrome, but the behavior is the same on Firefox and Safari too.

https://user-images.githubusercontent.com/96055551/159688426-0293f58f-69c6-429d-8f98-095180916619.mp4

**Comment by PatelUtkarsh** [comment]
Hello @felipebochehin87, Thank you for checking.

Padding is controlled by template editor:

https://user-images.githubusercontent.com/5015489/159690864-02366f5e-f261-4101-bfbe-92d1c39c25e8.mp4

**Comment by igruszkauy** [comment]
I have verified the use of the search block for header and it looks good
