### ISSUE TITLE
[FSE] Hamburger Menu Block for Header Block

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#235]
## Feature description

Create a Hamburger Menu Block to replicate the current header

![image](https://user-images.githubusercontent.com/5874851/140177718-b62492a6-ee1c-477c-b0aa-3cf53f606a70.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. User is able to manage the Hamburger Menu

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Try with providing editable hamburger menu, fallback to dynamic.

**Comment by felipebochehin87** [comment]
@PatelUtkarsh @emeaguiar good afternoon! Please find below a video with some issues:

1. When I make the text bold/italic, the FE displays the tags instead of displaying the text formatted;
2. While editing the hamburger menu text, when I make a the title and the subtext bold or bold and italic, these texts are set to bold or bold and italic. However, settings on the third text (the one right above the button in the video below) are not being applied. The text remains regular;
3. Missing scroll bar - image attached;
4. The title doesn't change, no matter if I set H1, H2, ... or H6, the text is displayed always on the same size - image attached.


![h1 h2 h3 ](https://user-images.githubusercontent.com/96055551/161776130-167f7ac6-e8c6-442b-aee0-b6d8781d4d4d.png)


![no scroll](https://user-images.githubusercontent.com/96055551/161776141-4740f0b7-4e25-4697-b5ee-520ec19754a7.png)


https://user-images.githubusercontent.com/96055551/161776176-5e30c320-1573-4fc1-9131-8eec5934f72d.mp4


CCing @igruszkauy

**Comment by felipebochehin87** [comment]
Ready for UAT. @igruszkauy 

Thanks @emeaguiar @PatelUtkarsh

**Comment by igruszkauy** [comment]
@emeaguiar I have found some issues for you to review:

- When comparing with non fse: 
  - Close button is missing on hover style
  - The menu is missing the on selected style
  
- When I go to page template I see the material title and close button duplicated many times
<img width="836" alt="image" src="https://user-images.githubusercontent.com/2902880/162569474-a15348b7-6145-40e0-9cee-3e0589ff2121.png">

- I have added the site logo in the menu but that’s not displayed on the frontend of the page
<img width="951" alt="image" src="https://user-images.githubusercontent.com/2902880/162569485-3ae74398-4ea7-4e68-a89d-0389b9545117.png">

- Tagline is different on both header and hamburger menu
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2902880/162569498-96ebd647-82c8-4b65-97ec-40cb216332e2.png">

**Comment by emeaguiar** [comment]
@igruszkauy I'm not really sure these are issues:

>Close button is missing on hover style

This seems to be happening in both fs and non-fse sites, hover effect is not present on first load but it appears after clicking it for the first time, may be the component itself

![Screen Recording 2022-04-12 at 09 46 15 a m](https://user-images.githubusercontent.com/1379732/162990027-192f6030-c0aa-4f43-bcf1-5ac9b7cc0558.gif)

>The menu is missing the on selected style

I'm not sure I understand this one, what is "style" referring to?

> When I go to page template I see the material title and close button duplicated many times

They seem to have been added several times, maybe in testing? they need to be removed.

> I have added the site logo in the menu but that’s not displayed on the frontend of the page

I see a second menu has been added to the content, the one available in the header bar has no logo. The other one must be hidden by the bar, only one menu is supposed to be used though.

![Screen Recording 2022-04-12 at 09 36 21 a m](https://user-images.githubusercontent.com/1379732/162987705-da3a2514-20ac-4be4-9d93-bae1d4855972.gif)

> Tagline is different on both header and hamburger menu

Those are different components, in the header is a tagline, in menu, it's a paragraph with custom text

<img width="566" alt="Screen Shot 2022-04-12 at 9 39 18" src="https://user-images.githubusercontent.com/1379732/162988609-efa954dd-89d8-4e51-aca0-98c0897d42d0.png">

**Comment by igruszkauy** [comment]
1. Close button is missing on hover style

> This seems to be happening in both fs and non-fse sites, hover effect is not present on first load but it appears after clicking it for the first time, may be the component itself
I see that, it seems that it only shows after you click that one time

2. The menu is missing the on selected style
> I'm not sure I understand this one, what is "style" referring to?
When you select an item in the main navigation for example "Blog" it should be also selected in the hamburger menu, also if you navigate from the hamburger menu to a page, that page should be "selected" in the menu. See screen from local environment:
![image](https://user-images.githubusercontent.com/2902880/163008780-6be1cbd8-aacb-48f6-87dd-00c0c9dcf8f1.png)

3. When I go to page template I see the material title and close button duplicated many times
> They seem to have been added several times, maybe in testing? they need to be removed.
We might need to look into, as they are displayed in the editor but NOT on the frontend? Also I have tried to remove them and after saving and reloading and even restoring customizations, those are shown again

4. I have added the site logo in the menu but that’s not displayed on the frontend of the page
>I see a second menu has been added to the content, the one available in the header bar has no logo. The other one must be hidden by the bar, only one menu is supposed to be used though.
https://user-images.githubusercontent.com/2902880/163010321-9dc00793-549f-4c67-a428-ce4280021606.mov

5. Tagline is different on both header and hamburger menu
> Those are different components, in the header is a tagline, in menu, it's a paragraph with custom text
I added a site tagline in the hamburger menu but that's not displayed on the frontend. However, on non fse, If I update the tagline it does update the header and hamburger menu
![image](https://user-images.githubusercontent.com/2902880/163019223-e2e03ce4-a6fe-449a-a451-f23a1521d3ca.png)

**Comment by PatelUtkarsh** [comment]
Hello @emeaguiar, Can you review last comment? ☝️

**Comment by emeaguiar** [comment]
I pushed #372 to handle the missing active indicator.

I also removed the duplicated hamburger menu from the testing site, as all the rest of the issues seem related to it, I've been trying to get it to appear locally but haven't been able to

**Comment by PatelUtkarsh** [comment]
@igruszkauy Above changes are deployed to fse site: fse-mdc-web.pantheonsite.io.
