### ISSUE TITLE
FSE - Card Collection

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#237]
## Feature description

Support a Card Collection block for archive pages

Current card: 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/5015489/140276800-cbde5cc8-a177-4d06-a328-cc1bb13661ea.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Page templates are able to support card collections as required for archive pages.
2. User should be able to edit / remove each card component (Featured image, title, Date, Summary, Author image, author name and comments block)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by igruszkauy** [comment]
[Verified via https://fse-mdc-web.pantheonsite.io/fse-card-collection237/](https://fse-mdc-web.pantheonsite.io/wp-admin/site-editor.php?postType=wp_template&postId=material-design-google%2F%2Farchive)

OK / Card Collection for Query Loop is added to the archive page
![image](https://user-images.githubusercontent.com/2902880/151182315-f49f53aa-41dd-4247-8d5d-88a940fe761d.png)

OK / User can add a Card Collection for Query Loop to a template![image](https://user-
![image](https://user-images.githubusercontent.com/2902880/151183047-f6a6c1b8-9270-43e6-a92d-ac9281e06e32.png)

NOT OK / User cannot hide featured image and title
![image](https://user-images.githubusercontent.com/2902880/151183268-7893fb70-6072-4c6e-a763-582c1691ac6d.png)

NOT OK / When editing the archive template, if I click to edit the configuration of a card, I get the header and sidebar duplicated and then a error is received
https://user-images.githubusercontent.com/2902880/151182225-4d9e5f76-f425-4b5e-b7ce-8ff845cacc19.mp4

**Comment by PatelUtkarsh** [comment]
Added option to hide featured image and post title. 

Trying to reproduce issue with archive duplicating header.

**Comment by igruszkauy** [comment]
@PatelUtkarsh I also see some differences in the style with material theme. 
Material theme > 2 columns 
![image](https://user-images.githubusercontent.com/2902880/151267699-09ce8479-a7af-45a4-94e6-e7e8a56e404b.png)

FSE > 3 columns, if I reload the page the borders have no radius and there is no margin between cards 
![image](https://user-images.githubusercontent.com/2902880/151267674-26dfc1d4-d005-4f7b-804c-55b1d7080e44.png)

Is this expected to be tackled as part of "requires-css"?

**Comment by PatelUtkarsh** [comment]
@igruszkauy Can you share the page URL for 3 columns?

**Comment by igruszkauy** [comment]
@PatelUtkarsh Sorry, here is the URL: https://fse-mdc-web.pantheonsite.io/category/block/

**Comment by PatelUtkarsh** [comment]
Masonry issue can be reproduced with regular theme: https://dev-mdc-web.pantheonsite.io/category/block/

**Comment by PatelUtkarsh** [comment]
Todo: Add elevated or outlined option.

**Comment by felipebochehin87** [comment]
LGTM.
