### ISSUE TITLE
[FSE] Clean up Existing Templates

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#243]
## Feature description

Setup the theme.JSON file for FSE

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Remove duplicate CSS variables from CSS in theme.JSON 
2. @jauyong to create a separate ticket for this: If we are going to support backwards compatibility we will need to handle the footer, post templates and header accordingly. 
   1. Based on the estimated release time of WP core FSE and ours, we will want to support this. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
putting this in the backlog for when we want to drop backwards compatibility.

**Comment by igruszkauy** [comment]
Closing as it's not needed.

**Comment by PatelUtkarsh** [comment]
We can reopen when we want to move site to FSE only.
