### ISSUE TITLE
on windows 11,  'npm install' return error

### ISSUE THREAD

**Issue by lbgitjp** [material-components/material-design-for-wordpress#248]
## Bug Description
on windows 11.
run:
`'npm install'`
return:

```
> postinstall
> node node_modules/puppeteer/install && composer install

Chromium is already in D:\test\material-design\node_modules\puppeteer\.local-chromium\win64-756035; skipping download.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
28 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> SlowProg\CopyFile\ScriptHandler::copy
Copied file(s) from plugin/tests/wp-tests-config.php to vendor/xwp/wordpress-tests/phpunit/wp-tests-config.php.
> if [ ! -f .git/hooks/pre-commit ]; then vendor/xwp/wp-dev-lib/scripts/install-pre-commit-hook.sh; fi
Script if [ ! -f .git/hooks/pre-commit ]; then vendor/xwp/wp-dev-lib/scripts/install-pre-commit-hook.sh; fi handling the setup event returned with error code 1
Script @setup was called via post-install-cmd
npm ERR! code 1
npm ERR! path D:\test\material-design
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node node_modules/puppeteer/install && composer install
```
because composer install will run file 'install-pre-commit-hook.sh'

but this file can't run success on win11.

on ubuntu, it is ok.

## Expected Behaviour

run success.

## Steps to reproduce

1. install Docker desktop
2. install chocolatey
3. choco install nodejs --version=16.13.0
4. choco install php composer docker-compose
5.  git clone git@github.com:material-components/material-design-for-wordpress.git material-design
6. cd material-design
7.  npm install
8. error return.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS: windows 11
 - Browser: chrome
 - Device: window pc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Hello @lbgitjp, Can you comment following line in package.json and re-try? Also, run `composer install` post `npm install` manually.

https://github.com/material-components/material-design-for-wordpress/blob/06b8aaae5ef7ce614c57b6b1f179e349dc5e860e/package.json#L181

Note: Current local setup isn't supported in windows, There is a potential task to support that in https://github.com/material-components/material-design-for-wordpress/issues/146 (It will be created as new task, but the timeline is unknown at this moment). 

You can however use [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/) to set up it locally in windows.

**Comment by lbgitjp** [comment]
i run 'npm install', it is ok.
then run 'composer install', return the same error.

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
28 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> SlowProg\CopyFile\ScriptHandler::copy
Copied file(s) from plugin/tests/wp-tests-config.php to vendor/xwp/wordpress-tests/phpunit/wp-tests-config.php.
> if [ ! -f .git/hooks/pre-commit ]; then vendor/xwp/wp-dev-lib/scripts/install-pre-commit-hook.sh; fi
Script if [ ! -f .git/hooks/pre-commit ]; then vendor/xwp/wp-dev-lib/scripts/install-pre-commit-hook.sh; fi handling the setup event returned with error code 1
Script @setup was called via post-install-cmd
```
thanks!
