### ISSUE TITLE
[FSE] FSE opt in option

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#255]
## Feature description

As a user, I want to opt in or out from using full site editing, so I can chose the mode I prefer to use for the theme (traditional or full site editing)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
1. An option via admin is provided for the user to opt in to full site editing mode when new version is out, providing a disclaimer - copy (to be approved) and link to read more: 

Admin notice
Description: Google Material Theme full site editing support is available. Please note this WordPress feature is currently in beta and testing on a separate environment is advised before enabling it in production. Read more
Read More link: https://developer.wordpress.org/block-editor/getting-started/full-site-editing/
CTA -  Enable / Maybe Later

2. Check if the user has permissions to edit the theme files, if so, switch the theme_disabled.json to theme.json
3. In other case, ask the user to manually rename the file
4. The option to ON/OFF switch FSE is provided via Material settings page (if plugin is active) or via a new theme settings page  - copy (to be approved): 

Title: Full Site Editing
Description: This setting won’t be available when Full Site Editing is out of Beta and fully supported by Wordpress.

5. This has dependency on WordPress

## Implementation brief

* 

## QA testing instructions

* 

## Demo

*

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, We will need copy for showing:
1. Admin notice to opt in.
1. Description for customize control.

**Comment by igruszkauy** [comment]
@rodydavis we have updated the AC based on what we discussed last week. We have also made some adjustments in the copy to make it more straightforward. Can you please approve this new messaging?

Admin notice
Description: Google Material Theme full site editing support is available. Please note this WordPress feature is currently in beta and testing on a separate environment is advised before enabling it in production. Read more
Read More link: https://developer.wordpress.org/block-editor/getting-started/full-site-editing/
CTA -  Enable / Maybe Later

Settings Page option
Title: Full Site Editing
Description: This setting won’t be available when Full Site Editing is out of Beta and fully supported by Wordpress.

**Comment by rodydavis** [comment]
Copy LGTM

**Comment by igruszkauy** [comment]
@PatelUtkarsh we can go ahead and finish the optin implementation

**Comment by PatelUtkarsh** [comment]
Hello @felipebochehin87, This is ready for testing. 

Since notice is only appearing once, you can test zip locally to check various scenarios.

Changes are also deployed to https://fse-mdc-web.pantheonsite.io. 

Here is full site editing build to test locally:

[material-design.zip](https://github.com/material-components/material-design-for-wordpress/files/8983815/material-design.zip)

[material-design-google.zip](https://github.com/material-components/material-design-for-wordpress/files/8983813/material-design-google.zip)

**Comment by felipebochehin87** [comment]
@igruszkauy looks good in QA. I tested locally installing the two zip files that @PatelUtkarsh added to a comment, then I reproduced the scenarios: Installed, didn't activate, activated, uninstalled, re-installed, clicked on Maybe Later, ...

Thanks @PatelUtkarsh for the call to explain :)
