### ISSUE TITLE
[FSE] Test FSE for backwards compatibility

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#256]
## Feature description

Material theme should be backward compatible with traditional theme if user opt out of full site editing or uses older version of WordPress ie. 5.8.

We need to test that everything is working.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Plugins and Theme should work with WordPress 5.8
- Plugins and Theme should work with full-site editing and non full-site editing mode. 
- Non-full site editing environment: https://traditional-mdc-web.pantheonsite.io/ - WP 5.9.
- Full site editing environment: https://fse-mdc-web.pantheonsite.io/ - WP 5.9.
- Validate FSE and non FSE theme doesn't break any existing functionality. 
- Validate settings provided in customizer for FSE theme are accurate, works properly. (Note, we will remove some settings from customizer for FSE and moved to block level in FSE).
- WP 5.8 will not support full-site-editing theme mode.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, I've updated AC, Can you please take a look?

**Comment by igruszkauy** [comment]
@PatelUtkarsh AC looks good, thank you. This can be tested together with FSE option ticket?

**Comment by PatelUtkarsh** [comment]
Yes, it can be tested except header part which is work in progress. @igruszkauy

**Comment by igruszkauy** [comment]
@felipebochehin87 as per the comment above, this can be tested except header part which is work in progress.

**Comment by felipebochehin87** [comment]
LGTM.
