### ISSUE TITLE
[FSE] Image list layout for Query Loop

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#298]
## Feature description

Create a new Query Loop template to support the post layout "Image List" provided in Customizer
![image](https://user-images.githubusercontent.com/2902880/152132703-dd10dcb9-610b-46c7-8ecb-61298a97eaf1.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User is able to add "Image List" template layout for Query Loop 
* Posts Layout settings are removed from Customizer

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Example: https://fse-mdc-web.pantheonsite.io/wp-admin/site-editor.php?postType=wp_template&postId=material-design-google%2F%2Farchive 

https://fse-mdc-web.pantheonsite.io/category/block/

It doesn't work with material masonry layout: I will take a look. 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/5015489/159406538-2a602680-e864-40e9-96f4-3277c00223e3.png">

**Comment by PatelUtkarsh** [comment]
Fix added https://github.com/material-components/material-design-for-wordpress/pull/323.  Deployed to FSE site to test.

Issue only appearing on Firefox.

**Comment by felipebochehin87** [comment]
@PatelUtkarsh looks good to me, thanks.

@igruszkauy please, what should we expect on the list view? Is this looking good or should we have any different behavior?

1. Checked list and grid view
2. Checked Masonry and default views

https://user-images.githubusercontent.com/96055551/159696067-fe91efa7-9624-4c99-ad06-462545e50c2e.mp4



https://user-images.githubusercontent.com/96055551/159696062-b4976e73-a916-4950-a3c3-bc2a8798109c.mp4

**Comment by igruszkauy** [comment]
@PatelUtkarsh couple of questions:

- How can I make the list display in two columns as we have for non fse? https://fse-mdc-web.pantheonsite.io/category/block/ vs https://dev-mdc-web.pantheonsite.io/category/block/
- I don't seem to be able to find where to switch title, description etc for the grid view. This was available through "show/hide post information
now: ![image](https://user-images.githubusercontent.com/2902880/159724968-95f2d136-0ee9-4011-bfff-92b81f0ff6fa.png)
before:
![image](https://user-images.githubusercontent.com/2902880/159725068-556bb659-8e97-487f-93df-23fb459f4931.png)

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, 

1. Select query loop from bottom and change columns to 2. Screenshot attached:
2. Image card doesn't have option to show / hide fields, We have those options in material card.


<img width="302" alt="image" src="https://user-images.githubusercontent.com/5015489/159909390-98f455a3-c366-4abc-92f5-e5eb04b606c2.png">

**Comment by igruszkauy** [comment]
@PatelUtkarsh this looks good, is there anything else that you think we should verify?
