### ISSUE TITLE
Add large size option to button

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#30]
## Feature description

As a site editor I want another button variation

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Follow Material guidelines for sizing: https://material.io/components/buttons-floating-action-button
2. Add a size section above "variations"
   1. Add options: regular, large(add padding)
3. Only show the size section when button style = text and variation != text  
4. Use primary color by default
 
![image](https://user-images.githubusercontent.com/5874851/115897706-b65c0e00-a42a-11eb-923f-2324f205d697.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
@dawidmlynarz to provide design on how option would look.

**Comment by dawidmlynarz** [comment]
@PatelUtkarsh please find attached the option to resize the button as well ass the new padding dimensions.

Paddings:
<img width="232" alt="Screenshot 2021-04-30 at 09 37 09" src="https://user-images.githubusercontent.com/8026823/116663792-e01bb480-a997-11eb-8b68-d9725245d1be.png">

Size select:
<img width="248" alt="switcher" src="https://user-images.githubusercontent.com/8026823/116663791-e01bb480-a997-11eb-9310-d97354966b52.png">

**Comment by PatelUtkarsh** [comment]
@csossi This also updates all patterns which has large call-to-action button.

**Comment by csossi** [comment]
Verified in QA
