### ISSUE TITLE
[M3] Color Tokens

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#313]
## Feature description

Tokens migration from M2 to M3

**Following the [Material.io guidance](https://material.io/)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- All existing tokens migrated from M2 to M3
- References updated in code
- New roles are available as described in https://m3.material.io/foundations/design-tokens/overview
- Updated components 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
List of color tokens: https://m3.material.io/styles/color/the-color-system/tokens#7fd4440e-986d-443f-8b3a-4933bff16646

**Comment by PatelUtkarsh** [comment]
@felipebochehin87 Note: this removes dark mode toggle, We will add it back soon.

**Comment by igruszkauy** [comment]
> Validate source color change generates all other colors and is able to preview in customizer. OK


@emeaguiar / @PatelUtkarsh 
A couple of questions:
- Is it ok that we have both tokens applied? Example for header we have --mdc-theme-primary and--md-sys-color-primary
![image](https://user-images.githubusercontent.com/2902880/177970573-abd77548-d69b-4cfd-bd87-704f97f372b0.png)
- How can I verify the secondary, tertiary, etc colors are saved and applied in the frontend? I can see the tokens are in the css.

Also:
- Can we move the "Random" icon to be closer to the color input?
![image](https://user-images.githubusercontent.com/2902880/177970909-ea7bbfc0-a31b-4394-8ac3-c3b592c5c47b.png)
- After changing the source color and updating the site, If I go to edit the homepage in the editor I am still seeing the "old" colors
![image](https://user-images.githubusercontent.com/2902880/177972687-93fc685c-3ba7-4069-8cb4-e3fccd73fedf.png)

**Comment by PatelUtkarsh** [comment]
> Can we move the "Random" icon to be closer to the color input?

This is merged.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/5015489/178417537-01791a35-7014-4e7e-a9be-2dc306bc2aa1.png">

**Comment by felipebochehin87** [comment]
@igruszkauy does it look good to you?

![closer](https://user-images.githubusercontent.com/96055551/178469076-b0a0bbac-9ab5-4aa2-93c2-2e6cab3e5dd9.png)


![colors](https://user-images.githubusercontent.com/96055551/178469096-9fbde417-a51b-42d3-8572-767788100bbe.png)

**Comment by igruszkauy** [comment]
@felipebochehin87 looks good !
