### ISSUE TITLE
[M3] Typography Tokens simplification

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#314]
## Feature description

Update typography to match M3 scale and tokens

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All font variations are updated to M3 new classification as described in https://m3.material.io/styles/typography/tokens
* Items that don't have a correspondent are migrated to the closest equivalent
* Customizer is updated to accept fonts to be customized for specific sections
* Allow users to change line height, font weight, font size, tracking, and font family
* Typography is mapped as follows:
    ['display2', 'displayLarge'],
    ['display3', 'displayMedium'],
    ['headline1', 'displaySmall'],
    ['headline2', 'headlineLarge'],
    ['headline3', 'headlineMedium'],
    ['headline4', 'headlineSmall'],
    ['headline5', 'titleLarge'],
    ['subhead1', 'titleMedium'],
    ['subhead2', 'titleSmall'],
    ['body1', 'bodyLarge'],
    ['body2', 'bodyMedium'],
    ['caption', 'bodySmall'],
    ['button', 'labelLarge'],
    ['overline', 'labelMedium'],
    ['labelSmall', 'labelSmall'],

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
In material plugin, For each group of role - Should we have common font face picker or should have it separate for each one? (In other words, Should display large, display medium and display small can have single font picker for simplification?) @igruszkauy

**Comment by igruszkauy** [comment]
@PatelUtkarsh I think this makes sense, unless there is a scenario where the user would want to use different font-face. We can check this with Rody

**Comment by PatelUtkarsh** [comment]
Mapping from M2 to M3.

``` 
    ['display2', 'displayLarge'],
    ['display3', 'displayMedium'],
    ['headline1', 'displaySmall'],
    ['headline2', 'headlineLarge'],
    ['headline3', 'headlineMedium'],
    ['headline4', 'headlineSmall'],
    ['headline5', 'titleLarge'],
    ['subhead1', 'titleMedium'],
    ['subhead2', 'titleSmall'],
    ['body1', 'bodyLarge'],
    ['body2', 'bodyMedium'],
    ['caption', 'bodySmall'],
    ['button', 'labelLarge'],
    ['overline', 'labelMedium'],
    ['labelSmall', 'labelSmall'],
```

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, 

Note: I have mapped reverse mapped font instead of using default from for new token https://m3.material.io/styles/typography/tokens

Meaning display small will use default values from `headline1` which is defined in theme.

For display large and display medium, I have kept font size as 120 and 110 respectively and kept other font property same as display small. (display large and medium are not directly used in any context by theme or plugin).

Question related to typography: Currently, we do not allow editor to pick font in Gutenberg. Should we add functionality to allow editor to pick m3 tokens / fonts?

**Comment by felipebochehin87** [comment]
Looks good to me. More dev and QA work to be complete in https://github.com/material-components/material-design-for-wordpress/issues/352

**Comment by igruszkauy** [comment]
@PatelUtkarsh don't we have option to select the line-height and tracking? I am only seeing size and style:  
![image](https://user-images.githubusercontent.com/2902880/169854865-f240304d-6712-4b19-93ab-ced0e148a286.png)

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, The screenshot is from m2 tokens in which we did not provide those options.

**Comment by igruszkauy** [comment]
@PatelUtkarsh I have now tested on https://dev-mdc-web.pantheonsite.io/wp-admin/customize.php and the tokens and properties look good.
I have two recommendations:
- Put size first in the list of properties
- Leave some more space between the different typographies (display large, medium etc)

@felipebochehin87 can you confirm you tested in this environment?

**Comment by felipebochehin87** [comment]
@igruszkauy yep, that was the one I used. Approving this PR and retesting the items above when 359 is ready.
