### ISSUE TITLE
[M3] Dynamic colors

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#315]
## Feature description

Support for dynamic colors

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* Primary, Secondary colors selection available in customizer
* https://www.npmjs.com/package/@material/material-color-utilities package is integrated in customizer hooked with color color selection
* When the user selects one of the colors it will generate the theme and 
  * Manual and light / dark colors are overridden
  * User needs to go back to reselect any manual colours if needed

Note: Dependent on tokens being done 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by felipebochehin87** [comment]
@igruszkauy looks good in QA. Would you please confirm?

I edited fonts, colors, button types, etc. I inspected the source code and saw the tokens, the primary, secondary, tertiary and neutral colors.

**Comment by igruszkauy** [comment]
@emeaguiar / @PatelUtkarsh some comments:

- The preview in the editor shows the "old" color
![image](https://user-images.githubusercontent.com/2902880/177974568-4e20ef50-40ea-4fdd-bd0b-06eee6f60229.png)
- If I change the container color for a button, and then try to set the primary color, I go back to the "old" color and not the primary 
- I am only able to select primary and secondary colors, I should be able to also select tertiary and neutral ones, right?
![image](https://user-images.githubusercontent.com/2902880/177974775-f0be5e34-9b07-4248-9d92-f88af5c96af9.png)

Usability:
- I found it hard to understand the behavior of the color picker. I would expect to be able to change the color when clicking on the color box, similar to what we do in the customizer. Also, it would be more intuitive if when clicking on the color container it would open the color palette and custom color together, also in the same way as customizer 
<img width="290" alt="image" src="https://user-images.githubusercontent.com/2902880/177976659-30c44a75-2829-4910-8d47-38d8444b7fd9.png">
- When I open the color palette I can't close it unless I click again on the Color palette link. I think we should provide an alternative way of closing, for example clicking outside

**Comment by emeaguiar** [comment]
Hi @igruszkauy 

> I am only able to select primary and secondary colors, I should be able to also select tertiary and neutral ones, right?

This is not in scope (for now) but it is planned in the future, we should probably remove that from the acceptance criteria at this point and create a new ticket to extend the colors.

> The preview in the editor shows the "old" color
> If I change the container color for a button, and then try to set the primary color, I go back to the "old" color and not the primary

These are bugs, working on them

> I found it hard to understand the behavior of the color picker. I would expect to be able to change the color when clicking on the color box, similar to what we do in the customizer. Also, it would be more intuitive if when clicking on the color container it would open the color palette and custom color together, also in the same way as customizer

This was made to be different from customizer, BUT it should align with WordPress' behavior, which seems to have changed, I'll see if we can mimic something like the current one:
 
<img width="618" alt="Screen Shot 2022-07-08 at 11 41 20" src="https://user-images.githubusercontent.com/1379732/178034711-e9ac8db0-b401-4e9d-af8d-77f799f9429f.png">

**Comment by PatelUtkarsh** [comment]
@igruszkauy @emeaguiar Should we close this one?

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/2744-2/

1. Added a paragraph, I can change the color and background using M3 colorshttps://dev-mdc-web.pantheonsite.io/2744-2/
2. When updating source color from customizer, the color and background from paragraph are updated
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/2902880/186709178-eaf90fe6-e32f-4a79-b40e-4fa95a8b9fe9.png">

Known issues that need to be handled by core:
1. Name of the color to be more user friendly
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/2902880/186709747-a6d57e35-52ef-4922-a744-bfd688d96ca9.png">

2. Color of the font for the name of the color is white and can't be seen when selecting a light color
<img width="706" alt="image" src="https://user-images.githubusercontent.com/2902880/186709772-baf6ff35-00d2-4e60-b7a0-6f5b889bdc88.png">

**Comment by igruszkauy** [comment]
Closing this ticket as it has already been tested as part of https://github.com/material-components/material-design-for-wordpress/issues/354
