### ISSUE TITLE
[M3] Components - Tab

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#324]
## Feature description

Update Tab component to match M3 style

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tab block is replaced with m3 specs as provided by MDC
* When the user opens Gutenberg page with m2 component it automatically migrates to M3

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Tab require migration from m2 to m3 since typography class is changes as per https://github.com/material-components/material-design-for-wordpress/pull/370/files#diff-858e445f1f1095a52fdf04e1505b6d33eca98e9eb4e0c27d909e1d75dea6f9a5

**Comment by PatelUtkarsh** [comment]
QA note: Test material tab block with m3 typography and color token.

**Comment by igruszkauy** [comment]
Verified via local environment and zips provided for M3 version:
M2: 
![image](https://user-images.githubusercontent.com/2902880/184726519-4af541a8-fc6a-4f70-82e0-2e7598ed4180.png)

After updating M3:
![image](https://user-images.githubusercontent.com/2902880/184727226-0968f9d1-05e0-453f-a96b-babe8d5c28f4.png)

- I think there is an issue, the component doesn't display correctly on dark mode, the titles are in black and cannot be read properly. Also, when changing the source color it applies the dark scheme and the switch behaves in a strange way

https://user-images.githubusercontent.com/2902880/184730288-b67d528b-eefc-4a23-9e37-04985f959a8c.mov

 - Verified changing typography works:
![image](https://user-images.githubusercontent.com/2902880/184730595-f3761729-9264-4221-a9d6-6028537a0286.png)

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy Good catch, I've already created PR for that fix #418, I found the issue while preparing for demo.

**Comment by igruszkauy** [comment]
After adding the tab and going to the page if I go to customizer and change the source color, it still has some issues with the color of the inactive tabs, unless I go and change the dark/light mode

https://dev-mdc-web.pantheonsite.io/tab-test/
https://user-images.githubusercontent.com/2902880/185611046-ec550815-d312-4ea3-911c-4f91df24158c.mov

**Comment by PatelUtkarsh** [comment]
Good catch @igruszkauy, 

This is because when re-generating color on customizer, we are not computing and injecting RGB CSV value which is used at various places. This is not specific to tab, I will create a new PR to fix this. 

More details on this comment: https://github.com/material-components/material-design-for-wordpress/issues/330#issuecomment-1188559276

**Comment by igruszkauy** [comment]
verified via: https://dev-mdc-web.pantheonsite.io/tab-test/

Issue fixed: After adding the tab and going to the page if I go to customizer and change the source color, it still has some issues with the color of the inactive tabs, unless I go and change the dark/light mode
