### ISSUE TITLE
[M3] Components - List

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#327]
## Feature description

Update List component to match M3 style

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* List block is replaced with m3 specs as provided by MDC 
* When the user opens Gutenberg page with m2 component it automatically migrates to M3

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
QA note: Test material list block with m3 colour and typography.

**Comment by igruszkauy** [comment]
@PatelUtkarsh 

1. The list is displayed correctly and the styles are as follows:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/2902880/184408511-b4a54076-2fd3-4b80-a645-cdb58f1fbba3.png">

2. I can change typographyusing the new tokens from customizer and it works as expected
<img width="981" alt="image" src="https://user-images.githubusercontent.com/2902880/184409903-7404b290-c494-4a9d-815c-c20be7b2edad.png">

Not sure how to test the block using the m3 colours?
Anything else that needs to be verified?

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, To test block with m3 
1. Use the latest zip 
2. Generate colour using customizer once
3. Save 
4. View block being tested.

**Comment by igruszkauy** [comment]
@PatelUtkarsh the components looks good:
M2: ![List](https://user-images.githubusercontent.com/2902880/184863330-1f77bbb6-23ec-4283-a754-4dd3fbcff010.png)
After updating to M3: ![List](https://user-images.githubusercontent.com/2902880/184863354-770105bb-f208-4f2a-ba60-f68c8240e1ae.png)

Just one note: The color palette does not affect this component. Is this as expected?

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, Can you share m3 list url on dev-mdc-web.pantheonsite.io? I think we should check once with Rody about colors.

**Comment by igruszkauy** [comment]
@PatelUtkarsh Sharing link https://dev-mdc-web.pantheonsite.io/list/

**Comment by PatelUtkarsh** [comment]
Hello @rodydavis, Can you review list block color? https://dev-mdc-web.pantheonsite.io/list/

**Comment by rodydavis** [comment]
Color looks good!

**Comment by igruszkauy** [comment]
Closing this ticket per Rody's comment above.
