### ISSUE TITLE
[M3] Components - Gallery Masonry

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#329]
## Feature description

Update Gallery Masonry component to match M3 style

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Gallery Masonry block is replaced with m3 specs
* When the user opens Gutenberg page with m2 component it automatically migrates to M3

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
https://user-images.githubusercontent.com/5015489/181432006-5abc9870-382e-4abe-a241-afe401805a04.mp4

**Comment by felipebochehin87** [comment]
Issue found: ID 396.

**Comment by PatelUtkarsh** [comment]
Hello @felipebochehin87, Can we move this one forward and track the issue with multiple masonry in #396?

**Comment by felipebochehin87** [comment]
Sure, I'll run another round of QA and let you know. If I find something else I'll kick back this one. If not, I'll move to UAT :) thanks!

**Comment by felipebochehin87** [comment]
This is what I see in a fresh install (having installed version 0.6.1 plugin and theme). This doesn't happen in an existing (old) site. We have this issue besides the one in ticket 396.

![image](https://user-images.githubusercontent.com/96055551/182364507-dd9ba157-7ac6-4b7b-af53-487cdc9bd01d.png)

**Comment by PatelUtkarsh** [comment]
Hello @felipebochehin87, The screenshot provided seems like for query loop block vs this should be used with material gallery, Can you double check?

**Comment by felipebochehin87** [comment]
@PatelUtkarsh that's correct. Sorry abt that. Moving to UAT.

@igruszkauy we have a known bug, 396. Outside of that, things look good to me. I added "Gallery (Material)" to the page to run this test.
