### ISSUE TITLE
[M3] Components - Image Card

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#331]
## Feature description

Update Image Card component to match M3 style

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Material image card block is replaced with m3 specs repurposing Material Card component (https://www.figma.com/community/file/1035203688168086460)
* When the user opens Gutenberg page with m2 component it automatically migrates to M3
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by felipebochehin87** [comment]
Some thumbnails are not loading. The only load when I click on them, and when one loads, another one disappears.


https://user-images.githubusercontent.com/96055551/181732161-69f997ae-d2a1-4c45-a3bb-d047134df82a.mp4

**Comment by PatelUtkarsh** [comment]
This is due to server side rendering component re-rendering on click, I've made edit component which will not re-render this on click. PR in code review #398 @emeaguiar

**Comment by PatelUtkarsh** [comment]
PR is merged and deployed to dev site which fixes the issue mentioned by @felipebochehin87 cc: @igruszkauy.

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/2717-2/
Image card displays as expected, I can change the styles and change the settings and works as expected:
![image](https://user-images.githubusercontent.com/2902880/185606835-b46cec85-a7e7-42f2-b852-0209ccee9f0c.png)

When I change the source color, it updates the colors used in the cards as expected:
![image](https://user-images.githubusercontent.com/2902880/185607066-a78371f6-5373-48a8-a0ad-ad57e1e1850b.png)

Updating typography works as expected:
![image](https://user-images.githubusercontent.com/2902880/185607199-e4678d58-8e91-4d78-8a5e-0f44375ae2e2.png)
