### ISSUE TITLE
Add 'useBlockProps' to material blocks.

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#339]
## Feature description

Add 'useBlockProps' to material blocks

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Use block props API to for WordPress plugin blocks: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#block-wrapper-props 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
@felipebochehin87 We can test all material blocks in this one:

1. Add block.
2. Save.
3. Load in frontend.

All 3 steps should not cause any error. 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/5015489/165095969-64a48200-b994-4bcb-85f1-ce4104564ad6.png">
