### ISSUE TITLE
[FSE] WP 6.0 RC 3 testing 

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#345]
## Feature description

Test FSE implementation with WP 6.0 RC 3

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* FSE templates, template parts and blocks are working as expected

## Implementation brief

* 

## QA testing instructions

1. Access https://wp-6-mdc-web.pantheonsite.io/wp-admin/ and log in as an Admin
2. Hover over Material Theming RC and open Visit Site in a new tab
3. On the Admin page, hover over Appearance and click on Editor
4. Being on the editor screen, test the items below:
    a. Templates
    b. Template parts
    c. Site
    d. Dark mode / light mode
    e. Preview
    f. Search
    g. Admin menu
    h. Layouts
    i. Paddings
    j. Texts
    k. Headers and footers
    l. Images
    m. Add elements
    n. Remove elements
5. For each change, click on "Save" and preview changes refreshing the site you opened in another tab on step 2

The expected here is:
* Everything should work as it does nowadays;
* We must have no layout issues;
* All changes made on the admin side should be visible on the web app once the page is refreshed;
* All buttons, links and other clickable elements must work;
* Search results must be compatible with the term used for search.

## Demo

* 

## Changelog entry

*

**Comment by igruszkauy** [comment]
1. When I go to page template the navigation and hamburger menu are not displayed in preview, but frontend looks good
![image](https://user-images.githubusercontent.com/2902880/169281334-22744c9b-fb70-4e05-b06d-928df45ee28a.png)
vs
![image](https://user-images.githubusercontent.com/2902880/169281395-7839daa9-3000-4d99-bed1-031bd9a7775d.png)
2. Close icon in hamburger menu is not displayed as expected
![image](https://user-images.githubusercontent.com/2902880/169281493-c16c7bf7-3533-4d3a-aeb7-c23791fae099.png)

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy,

1. Hamburger menu is state aware: If you open menu and save page and refresh, It will keep menu open and vice-versa. Current default state on fresh installation is open hamburger menu. (This state has no frontend effect).
2. Close button: This can be configured by not allowing wrap, as shown in screenshot. `Allow to wrap to multiplelines`. 
<img width="989" alt="Screenshot 2022-05-20 at 12 13 36 PM" src="https://user-images.githubusercontent.com/5015489/169469212-f7987368-66c9-480c-9ff0-acb2b34cd2bf.png">

**Comment by igruszkauy** [comment]
@PatelUtkarsh Confirmed this is working as expected
Assigning to @felipebochehin87 for a final review

**Comment by felipebochehin87** [comment]
@igruszkauy @PatelUtkarsh looks good to me in Chrome, Safari and Firefox.
