### ISSUE TITLE
[M3] Update all patterns with m3 components

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#347]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
- After all m3 components are merged, 
- Update all existing material patterns with m3 components, colors and typography.

## QA testing instructions

Insert pattern to editor, it should not throw any error or show broken blocks.

## Demo

* 

## Changelog entry

*

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/patterns-3/

Patterns are updated with tokens and displayed as expected. I can change color and typography and see that applied in the patterns as expected.

**Comment by igruszkauy** [comment]
@PatelUtkarsh this pattern is giving an error: 
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/2902880/186725437-e700c75f-81bc-4a51-9b0f-1ee93189d06f.png">

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, This mentioned pattern is fixed: 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/5015489/187213807-a542dc45-0604-4707-b74c-6124c0c914a5.png">

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/patterns-3/
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/2902880/187280128-b1ea387b-c4ff-427b-a00e-ff4788c71114.png">
