### ISSUE TITLE
[M3] Migrate fonts

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#351]
## Feature description

Migrate font settings used in customizer to M3

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Font settings in customizer are migrated to M3

## Implementation brief

* 

## QA testing instructions

When a user is coming from m2 settings: 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/5015489/166499609-69525295-1124-4761-a6ae-c093c32e5e29.png">

Appropriate settings should be migrated to m3 if user has changed any default values. 
* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Wrote migration for m2 settings - it will migrate when user visit admin page first time after m3 migration. 

Migrating font, size and style to m3 tokens as per mapping provided in #348 ticket. 

We can change when the script should trigger when we introduce wizard for informing m3 features.

**Comment by felipebochehin87** [comment]
Looks good to me.

https://wp-6-mdc-web.pantheonsite.io/wp-admin/customize.php?url=https%3A%2F%2Fwp-6-mdc-web.pantheonsite.io%2F

I was able to see and edit font and font size on Body & Captions and Headlines & Subtitles.

![H S](https://user-images.githubusercontent.com/96055551/169809624-41c3e6bd-0d23-4616-9ddb-426e4f1d7fe3.png)

![B C](https://user-images.githubusercontent.com/96055551/169809629-acc59dab-75c3-4681-8570-23ae43857937.png)

**Comment by igruszkauy** [comment]
@PatelUtkarsh is there a way we can have both font properties aligned? We could have size label above the select box maybe?

Also, the select seems to be a little bit small for some values, for example: Medium italic. Can we make it wider?
![image](https://user-images.githubusercontent.com/2902880/169852190-c5a41cba-a1ff-44cd-967d-b64723d71d4d.png)

I am not sure if I am testing properly, but I was not able to change the size of the captions, and when I change the font-family it does not apply:

https://user-images.githubusercontent.com/2902880/169853529-d178f694-79ff-46bd-aa52-df78ea6b37cd.mov

Uploading typography.mov…


QQ: What is the difference between body 1 and body 2?

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, Can you test this on https://dev-mdc-web.pantheonsite.io/wp-admin/customize.php ? 

FSE site has m2 tokens.

**Comment by igruszkauy** [comment]
Tested in https://dev-mdc-web.pantheonsite.io/wp-admin/customize.php and looks good

**Comment by felipebochehin87** [comment]
Looks good in Chrome, Safari and Firefox.
