### ISSUE TITLE
[M3] Font picker to support M3 tokens

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#352]
## Feature description

Allow users to choose M3 tokens from Gutenberg

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user can use M3 tokens from Gutenberg
* Font size picker is available in the sidebar when a text component is selected
* This also applies to the rest of the M3 properties for typography 

## Implementation brief

* Add m3 font in theme.json in theme. (Note currently we don't have that, so it may have other impact) Edit: For Backward compatibility we also need to add theme support with array of m3 `editor-font-sizes`.
* Font picker in Gutenberg should also handle tracking, line height and font weight (which are part of m3 tokens).
* Plugin can override the font class implementation to support custom values added by the user using plugin's customizer options.

## QA testing instructions

* Verify user is able to use m3 tokens from Gutenberg.
* Verify plugin customization can override token. (Example: Change title large font size and verify that is reflected when user pick title large in font selection in Gutenberg).

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Holding with me until we revert #360

**Comment by igruszkauy** [comment]
@PatelUtkarsh Verified I can select the new M3 font size from Gutemberg, however I don't see where I can select the rest of the properties?

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, Based on font it will automatically assign other properties which user selected for that token. For Example, If you set display large to an element, It will set font-weight, letter spacing etc for display large, so user don't have to make those choice in Gutenberg.

**Comment by igruszkauy** [comment]
@PatelUtkarsh this is totally fine, I was confused by the AC "This also applies to the rest of the M3 properties for typography"
