### ISSUE TITLE
[Pattern] Hero Section

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#36]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. base block should be a cover block with a set background color
![image](https://user-images.githubusercontent.com/5874851/114190327-2d68b100-9919-11eb-8917-a1f365e6c031.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
@dawidmlynarz @jauyong I've added a background color for the pattern, let me know if you want to use a different color

![Screenshot 2021-04-26 at 7 48 05 PM](https://user-images.githubusercontent.com/26096061/116098270-8f226c80-a6c8-11eb-965b-4ad11a263d86.png)

**Comment by csossi** [comment]
Can't seem to find this section in the Patterns tab on staging

**Comment by csossi** [comment]
Verified in QA
