### ISSUE TITLE
[M3] Shuffle source

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#366]
## Feature description

Provide a random color generator 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User can chose to generate source color randomly
* The rest of the colors will be updated based on the color generated

## Implementation brief

* Random color function:
```
const MAX_HEX_COLORS = 16777215;
/**
 * Generate a random seed color
 *
 * @return Hex color
 */
export function randomColor() {
  let hexColor = Math.floor(Math.random() * MAX_HEX_COLORS).toString(16);
  // Pad to make sure it's 6 characters.
  while (hexColor.length < 6) {
    hexColor = '0' + hexColor;
  }
  return '#' + hexColor;
}
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
This is handled in customizer by @emeaguiar in #349.
