### ISSUE TITLE
[Pattern] Hero Section + Image

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#37]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Image licensing is fair use

![image](https://user-images.githubusercontent.com/5874851/114190418-483b2580-9919-11eb-9278-73476b03839e.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
