### ISSUE TITLE
Color picker for material button doesn't work as expected

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#374]
## Bug Description

![image](https://user-images.githubusercontent.com/5015489/176740703-d9dff4c1-6b51-46cf-b52b-c1d4ccfd3989.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Handled in [09a1969](https://github.com/material-components/material-design-for-wordpress/pull/349/commits/09a1969bffd80578727184833db82d82c0c149ea)

**Comment by igruszkauy** [comment]
@PatelUtkarsh could you please add some details/steps to reproduce into the ticket? We are not sure which was the issue.
thank you!

**Comment by PatelUtkarsh** [comment]
Steps:

1. Add material button block.
2. Select color picker to change color.

**Comment by felipebochehin87** [comment]
Thanks @PatelUtkarsh 

@igruszkauy I tested changing, selecting, resetting the colors in https://dev-mdc-web.pantheonsite.io/wp-admin/post.php?post=2678&action=edit and it works for me. I don't see any bug.
