### ISSUE TITLE
Issues when user clicks 2 or 3 times on the same color

### ISSUE THREAD

**Issue by felipebochehin87** [material-components/material-design-for-wordpress#379]
## Bug Description

- Color picker disappears if user clicks 2 or 3 times on the same color;
- Icon Styles hides options but doesn't collapse the grid below it

## Expected Behaviour

Color picker must not disappear and Icon Styles must expand/collapse on each click.

## Steps to reproduce

1. Go to https://dev-mdc-web.pantheonsite.io/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php
2. Click on Material Design Options > Color Palette
3. Click on the color inside the circle to expand the list of colors available
4. Click 2 or 3 times on the same color - here the color picker disappears
5. Click on Icon Styles - see that the options are hidden/displayed, but the grid under the field title is not collapsing

## Screenshots

https://user-images.githubusercontent.com/96055551/177779580-426de4ec-55b4-4a30-81a4-0bcfee850510.mp4

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by emeaguiar** [comment]
Turns out the color picker allows deselecting colors by clicking a second time. I've added a default in case this happens
