### ISSUE TITLE
[Pattern] Logos

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#38]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/114190584-7456a680-9919-11eb-8dce-183e5f1ef7c3.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
seeing this in QA environment:
![image](https://user-images.githubusercontent.com/16945664/119980949-00d12d00-bf8b-11eb-83a1-cc1f93ca2dba.png)

**Comment by csossi** [comment]
Verified in QA
