### ISSUE TITLE
[M3] Set default corner radius

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#384]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
- When user upgrades from m2 to m3 - following radius should be updated to m3 default state. 
    - Data table: 24px
    - Card: 12px
    - Image card: 12px
- Update above as required with new m3 components.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
When migration happens from m2 to m3 - this will update corner radius value in customizer to reflect default values from m3. 

M2 was using 4px radius for all the component, while m3 uses different radius for different components.

**Comment by PatelUtkarsh** [comment]
To test this, create fresh site using m2 and then use latest m3 zip (activate plugin and theme) and validate corner radius is updated in customizer.

**Comment by igruszkauy** [comment]
Verified via local environment:
![image](https://user-images.githubusercontent.com/2902880/185747605-822c59a2-e28c-466d-86c9-3f30c42e0d53.png)
