### ISSUE TITLE
Masonry style displays one card above the other

### ISSUE THREAD

**Issue by felipebochehin87** [material-components/material-design-for-wordpress#396]
## Bug Description

Masonry style displays one card above the other, making it difficult to identify the cards that are hidden.

## Expected Behaviour

Cards should be more visible.

## Steps to reproduce

1. Go to https://dev-mdc-web.pantheonsite.io/wp-admin/
2. Go to Pages and click on Add New
3. Add a Query Loop > Material Image Card for Query Loop
4. Set it to Masonry and preview page

## Screenshots

![masonry](https://user-images.githubusercontent.com/96055551/181730009-8fac5f5e-9e9e-4e5f-a20e-666a9644d8b6.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by felipebochehin87** [comment]
@PatelUtkarsh @igruszkauy @mattchungxwp new bug found.

**Comment by PatelUtkarsh** [comment]
This issue happens when two masonry query loops are inserted on the same page / post.

**Comment by felipebochehin87** [comment]
@PatelUtkarsh thanks for clarifying :) that's the bug we talked about on our call last Friday. :)

**Comment by PatelUtkarsh** [comment]
QA note: 

1. In the same post / page, add the following block.
1. Add image card using query loop. 
1. Add material card using query loop. 
1. Add material gallery. 
1. Publish and test frontend.

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/masonry-style-test/

Issue fixed:
![screencapture-dev-mdc-web-pantheonsite-io-masonry-style-test-2022-08-20-09_53_55](https://user-images.githubusercontent.com/2902880/185747110-ea20befe-1030-4f5e-aa1c-5dd940320cbb.png)
