### ISSUE TITLE
Query loop selection doesn't load material icons

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#397]
## Bug Description
Query loop frame for picking post layout doesn't load material icons.

## Steps to reproduce
1. Insert new query loop block. 
2. Select choose template. 
3. See material card doesn't load material icons. 

## Screenshots

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/5015489/182156426-b61a6c6a-9c30-4adc-a28e-4ab4f5d8a03a.png">

## Additional context

 - WordPress version: 6.0.1
 - Plugin version: develop branch
 - Gutenberg plugin version (if applicable):
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/2739-2/

When adding query loop block, it shows the icons:
![image](https://user-images.githubusercontent.com/2902880/186702839-ee3581cd-7fe8-4971-849a-39aea36e35d5.png)

When updating the page, it shows the icons:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/2902880/186703077-2e0286b6-6b62-479d-8ec0-c6180fb43dee.png">
