### ISSUE TITLE
[Pattern] CTA + Benefits

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#40]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/114190898-d57e7a00-9919-11eb-8df8-a09bafbc1080.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
Updated the benefits to use 3 columns so it fits in the block editor without overflow.

![Screenshot 2021-04-23 at 7 24 49 PM](https://user-images.githubusercontent.com/26096061/115881658-9992fb00-a469-11eb-8862-c7c373239cba.png)

**Comment by csossi** [comment]
Verified in QA
