### ISSUE TITLE
[M3] Plugin update admin notice and color migration

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#400]
## Feature description

Upon plugin install, show admin notice or the user to select source color

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When user updates plugin an admin notice is displayed to notify the user the site has been updated to Material Design 3 and that the color palette is going to be generated using primary color.
* Admin notice shows the following message "Your site has been updated with Material Design 3. The color palette will be generated dynamically from primary color. You can preview the site and change the source color from customizer."
* Admin notice shows CTA "Go to Customizer", user can click to go to customizer, preview the site and select source color (navigate directly to color panel).
* While the notice is open: In background (in javascript), m2 primary color should be used to generate m3 color tokens and saved to the relevant customizer setting. (Assume that some user may skip this notice).

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
How about following? @igruszkauy 
> Your site is updated with Material Design 3,  The site's color palette will be generated dynamically from primary color, please go to customizer to change source color.

**Comment by igruszkauy** [comment]
@PatelUtkarsh I like it, what about making the following adjustments?

> Your site has been updated with Material Design 3. The color palette will be generated dynamically from primary color, please go to customizer to select a source color.

**Comment by igruszkauy** [comment]
@rodydavis can you please review the messaging? 

**Your site has been updated with Material Design 3. The color palette will be generated dynamically from primary color. You can can preview the site and change the source color from customizer.**

**Comment by rodydavis** [comment]
LGTM

**Comment by PatelUtkarsh** [comment]
For testing you can use zip from: https://github.com/material-components/material-design-for-wordpress/issues/325#issuecomment-1223808721

**Comment by igruszkauy** [comment]
Verified via local environment updating theme and plugin
1. Updated theme and plugin and verified admin notice is displayed and links to customizer
2. M2 primary color us used to automatically generate M3 colors
