### ISSUE TITLE
[M3] Component Checkbox

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#402]
## Feature description

Replace `@material/checkbox/dist/mdc.checkbox.css` M2 checkbox style with m3.

Checkbox is used within theme and to display material demo component within customizer.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
QA notes :

Checkbox is used on a comment template, for which you will need to view non-logged in post.

Open this in incognito: https://dev-mdc-web.pantheonsite.io/2022/02/01/quia-vel-enim-reprehenderit/

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/5015489/185546854-a4b01cfc-1124-4112-a6e2-47235802a898.png">

**Comment by igruszkauy** [comment]
Verified via https://dev-mdc-web.pantheonsite.io/2022/02/01/quia-vel-enim-reprehenderit/ in incognito mode

1. Shows ripple effect: <img width="591" alt="image" src="https://user-images.githubusercontent.com/2902880/185746190-f323f0ee-f89a-4d6e-b46e-f7989eb61924.png">
2. I was not able to verify changing color and typography with M3 tokens. From another tab logged w/user, I changed source color and published changes. Then went back to a new guest window and the post is showing the same colors, despite the rest of the site using the new ones. Also tried cleaning cache.
https://user-images.githubusercontent.com/2902880/185746441-2c371956-a8dc-4c03-bd5d-98d41b7f7a97.mov

**Comment by igruszkauy** [comment]
Update: testing updating M2>M3 in a local environment it works well and I was able to update both color and typography.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/2902880/185746680-69c251ef-1081-4457-82c8-53dc9501fbe0.png">

Sending ticket to "review" in case there is something we need to review

**Comment by PatelUtkarsh** [comment]
1. Yes ripple is expected.
2. This is odd, Should we create new ticket if we see this again and move this ticket forward? @igruszkauy
