### ISSUE TITLE
[Pattern] Features (button)

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#41]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. I am able to add the Features Pattern
2. It should resemble the mockup attached
3. After adding the pattern it should have all blocks added to the post/page with demo material including:
   1. Heading Block 
   2. Paragraph Block
   3. 3 columns including:
      1. Icon Block
      2. Heading Block
      3. Paragraph Block
      4. Button Block

![image](https://user-images.githubusercontent.com/5874851/114191028-f6df6600-9919-11eb-8a50-34716175acf0.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
