### ISSUE TITLE
M3 Switch

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#424]
## Feature description

Update switch component to m3

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation brief

* 

## QA testing instructions

* Only change is color from m2 to m3 for switch.
* Check if switch is working properly.
* Test switch with setting page: (Only used on these two pages)
    * `/wp-admin/admin.php?page=material-settings-page` 
    * `wp-admin/admin.php?page=material-onboarding-wizard` 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
QA instruction in description.

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/wp-admin/admin.php?page=material-settings-page

Settings page switch updates colors when changing source color
![image](https://user-images.githubusercontent.com/2902880/185609855-aeb6b5b3-6043-42d2-b860-ac1fe6de6ad1.png)

Verified via: https://dev-mdc-web.pantheonsite.io/wp-admin/admin.php?page=material-onboarding-wizard

Onboarding wizard swith updates color when changing source color from customizer
![image](https://user-images.githubusercontent.com/2902880/185610104-29207c02-c573-4096-8ce7-b561eac24973.png)
