### ISSUE TITLE
[M3] buttons are wrapping text

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#449]
## Bug Description

Buttons are wrapping text

## Expected Behaviour

Buttons should not wrap text

## Steps to reproduce

1. Go to https://dev-mdc-web.pantheonsite.io/material-blocks/
2. Check the buttons

## Screenshots

![image](https://user-images.githubusercontent.com/2902880/188764989-0d75f2d5-d086-431d-ab4f-7bef7e9a3fbd.png)

## Additional context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Note: This is edge case when too many buttons are added in the same line, We have added a fix which will allow buttons to wrap in a new line See [91f9dc1](https://github.com/material-components/material-design-for-wordpress/pull/452/commits/91f9dc148162d778ca19f9d951c96a80a69f6da4) and https://github.com/material-components/material-design-for-wordpress/pull/452/commits/1c66609c18cc8e37def12a2bd0d799728e4aa07e

**Comment by igruszkauy** [comment]
verified via: https://dev-mdc-web.pantheonsite.io/material-blocks/ 
![image](https://user-images.githubusercontent.com/2902880/188869057-a893ae99-aaae-4059-974b-1facb27c6914.png)
