### ISSUE TITLE
Update Settings for Card Collections Block

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#61]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 14:36 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/465_

----

## Feature description

~Review Global vs child settings in the block and compare to how we’ve handled it before(list block). 
See related ticket  #377 #496~

~Note: consider using the in context menu as opposed to the side bar with options~

Update the more settings side panel based on the mocks. 

Design Mocks:
![image](https://user-images.githubusercontent.com/5874851/111327474-cc182f80-8643-11eb-8de7-2ada315cb229.png)
![image](https://user-images.githubusercontent.com/5874851/111327572-dfc39600-8643-11eb-96ee-64215e2fc9f6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Side Panel settings should flow as follows:

1. Style
   1. Masonry
   2. List
   3. Grid   
2. Card Style
3. Corner Radius
4. Card Settings
   1. Content Layout
   2.  Cards Layout
   3. Columns
   4. Gutter
5. Content

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 17:28 GMT_

----

@jauyong to update AC to indicate we will do what we did for the list block

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Dec 18, 2020 at 16:52 GMT_

----

@jauyong to open new discovery ticket (list block) to inform this ticket.

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Thursday Jan 14, 2021 at 20:45 GMT_

----

Blocked temporarily until I can test out the `list` block. Requested @jauyong to open a ticket to investigate.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 12, 2021 at 16:44 GMT_

----

@dawidmlynarz to continue reviewing Joshua's mocks on #496

**Comment by jauyong** [comment]
This will be lowest priority in 0.3

**Comment by jauyong** [comment]
Note: the blue background on the warning may no longer be part of core so Mario used yellow instead

**Comment by PatelUtkarsh** [comment]
Here is before and after: 

Before: 

https://user-images.githubusercontent.com/5015489/137442828-f6ce4c66-a21c-4445-a01d-06621fd015cd.mp4

After: 

https://user-images.githubusercontent.com/5015489/137442820-0705009e-fd4c-4ad1-8509-a0cd0c0614ff.mp4

I've changed card style to elevation because that's a more appropriate word for it, which fits material guidelines.

@emeaguiar The gutter in mockup is with card settings section but we have it in card style, Is that something we should change or keep it?

**Comment by emeaguiar** [comment]
@PatelUtkarsh I'm not really sure why I didn't initially moved it, probably just missed the second image, I've created #224 to handle that

**Comment by PatelUtkarsh** [comment]
@csossi This is updated, Can you verify on test site?

**Comment by jauyong** [comment]
@csossi You can reference the mockups in the description for correct positioning of the settings.

**Comment by csossi** [comment]
Verified in QA
