### ISSUE TITLE
Icon buttons should have Material-styled tooltips

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#7]
<a href="https://github.com/jbingham"><img src="https://avatars.githubusercontent.com/u/563113?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbingham](https://github.com/jbingham)**
_Wednesday May 06, 2020 at 16:28 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/224_

----

## Bug Description

Material Icon Buttons currently show no tooltip when hovering.

## Expected Behaviour

When hovering over a button, it's expected that a tooltip will appear. Usually the text is redundant with the button, but sometimes it's actually useful, like if it's an icon button with no text.

![image](https://user-images.githubusercontent.com/3411173/86479789-ab9c8500-bd01-11ea-9366-4cab6a24d20c.png)

## Steps to reproduce

1. Create a new post.
2. Add a Material Button block to it and set to `icon`
3. Preview.
4. Hover the mouse over of the button.
5. Note that there's no tooltip.

## Additional context

The block editor would need a way to set the tooltip text. 

Note that the Material guidelines do include Tooltips. The material-components-web repo does not provide css for them, though that's in the works.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. When using an icon button, there is a way to set the tooltip display text
2. On the frontend when hovering over an icon button, the hover tooltip is displayed

## Implementation brief

* Add a new text field for button block which will show up only when the button is set to icon
* The tooltip content can be entered/saved in the new field
* Save component will save the tooltip markup

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Friday May 15, 2020 at 14:30 GMT_

----

Suggestion:

1. Have tooltip regardless of button style. View Material [guidelines](https://material.io/components/tooltips#placement).
2. Add an input field into the settings for the block when set to `style: icon`, which allows users to add the tooltip.

Adding the tooltip text should be done in context. Maybe replace the "label" text normally and have an indicator that it's an icon. Need to look at how some other icon block types do this.

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Monday May 18, 2020 at 20:34 GMT_

----

Related to #228

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Wednesday May 27, 2020 at 14:29 GMT_

----

@jbingham in the Material spec I'm only seeing tooltips on icon buttons for examples, none on text buttons. Should we allow users to add tooltips to both button types?

**Comment by ravichdev** [comment]
<a href="https://github.com/jbingham"><img src="https://avatars.githubusercontent.com/u/563113?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jbingham](https://github.com/jbingham)**
_Wednesday May 27, 2020 at 15:56 GMT_

----

Yes, I believe so.

@yasmineevjen can you confirm?

**Comment by ravichdev** [comment]
<a href="https://github.com/yasmineevjen"><img src="https://avatars.githubusercontent.com/u/11654612?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yasmineevjen](https://github.com/yasmineevjen)**
_Wednesday May 27, 2020 at 16:33 GMT_

----

Hey Joshua, we have a guideline to not use tooltips to restate visible UI text. (I would say let's **not** allow it for text buttons).

**Comment by ravichdev** [comment]
<a href="https://github.com/jbingham"><img src="https://avatars.githubusercontent.com/u/563113?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jbingham](https://github.com/jbingham)**
_Wednesday May 27, 2020 at 16:35 GMT_

----

What if the tooltips provide longer text? That would be acceptable, right?

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Wednesday Jun 24, 2020 at 17:06 GMT_

----

Just a thought, what if we had tooltips for the icon button only right now? That might solve the issue we're running into.

![Group 1](https://user-images.githubusercontent.com/3411173/85600516-69d55580-b602-11ea-9af6-7d8b03881656.png)

**Comment by ravichdev** [comment]
<a href="https://github.com/jbingham"><img src="https://avatars.githubusercontent.com/u/563113?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jbingham](https://github.com/jbingham)**
_Wednesday Jun 24, 2020 at 17:16 GMT_

----

Yes, that makes sense for now. Limit it to icon buttons.

**Comment by ravichdev** [comment]
<a href="https://github.com/ravichdev"><img src="https://avatars.githubusercontent.com/u/26096061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravichdev](https://github.com/ravichdev)**
_Tuesday Sep 22, 2020 at 11:14 GMT_

----

@jwold @jbingham @yasmineevjen @rodydavis  The tooltip option for an Icon button is added to the button block, we are using the `@material/tooltip` [package](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tooltip) which is in canary/edge release as of now.

![Screenshot 2020-09-22 at 4 40 57 PM](https://user-images.githubusercontent.com/26096061/93875368-79903300-fcf2-11ea-8391-3a61fd075b5f.png)

Should we put this feature on hold till the `@material/tooltip` package has a stable release ?

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Tuesday Sep 22, 2020 at 15:15 GMT_

----

I'll kick this back to backlog for now. We can always revisit when the package is stable.

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 17:19 GMT_

----

@jauyong to add new ticket for accessibility "Aria link". 
Possibly need to add new field in back for this link. 
We also may need to do a pass for accessibility. Review our components to see if they are descriptive enough for screen readers. Can consider adding aria labels where needed. 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

**Comment by ravichdev** [comment]
<a href="https://github.com/ravichdev"><img src="https://avatars.githubusercontent.com/u/26096061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravichdev](https://github.com/ravichdev)**
_Monday Mar 22, 2021 at 10:50 GMT_

----

@csossi This is ready for QA

**Comment by csossi** [comment]
Verified in QA
