### ISSUE TITLE
AMP Compatibility

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#77]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Thursday Feb 04, 2021 at 20:32 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/533_

----

## Feature description

Investigate how to make the theme and plugin compatible with the AMP plugin.

Note: This is regarding the plugin level, not the component level

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Compile a Google doc with findings that can be shared internally with the Google Team
2. In said doc, list out items that need to be done to achieve compatibility
3. Identify action items that are material specific vs theme vs plugin specific. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Tuesday Feb 16, 2021 at 19:35 GMT_

----

@rodydavis are you working with the AMP team directly now? Should we close this ticket?

**Comment by rodydavis** [comment]
We should close the ticket!
