### ISSUE TITLE
Add Icon via Paragraph

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#79]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Wednesday Feb 17, 2021 at 18:08 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/540_

----

## Feature description

As a site editor, I'd like to be able to add a Materical Icon while not using an `icon button`

See original slack conversation with Yasmine [here](https://xwp.slack.com/archives/CSS5LFZJB/p1613521802114500). 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. I am able to add an icon within a paragraph block without using an 'icon button' 
2. It should not have the tooltip
3. It should not have the ripple effect

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Feb 26, 2021 at 16:41 GMT_

----

@dawidmlynarz to create a design mock.

Here are my ROUGH notes.
1. add in text tool bar an icon button
2. popup icon list
3. then edit the hyperlink
4. colour should be the text colour

**Comment by ravichdev** [comment]
<a href="https://github.com/dawidmlynarz"><img src="https://avatars.githubusercontent.com/u/8026823?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dawidmlynarz](https://github.com/dawidmlynarz)**
_Wednesday Mar 03, 2021 at 11:52 GMT_

----

@jauyong Take a look at the proposal for how this could potentially work. I still need to design how to edit a hyperlink, but that will be a minor change and I will get back here with this update.

Please have a look at the prototype showing how to incorporate the icon picker inside of the toolbar and how it works. Let me know your thoughts!

https://user-images.githubusercontent.com/8026823/109801686-1bf7ff00-7c1f-11eb-990e-563969da9e00.mov

**Comment by jauyong** [comment]
@jauyong to create a ticket for adding an icon block

**Comment by PatelUtkarsh** [comment]
Only pending item is on delete with backspace, it adds additional space. @PatelUtkarsh to take a look.

**Comment by PatelUtkarsh** [comment]
Icon can be inserted via Inline Icon:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/5015489/131699389-e0888725-26c8-49fd-b0b2-a51c78520a69.png">

**Comment by csossi** [comment]
Verified in QA
