### ISSUE TITLE
Enable auto updates for plugin and theme

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#8]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwold](https://github.com/jwold)**
_Friday Aug 21, 2020 at 16:21 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/380_

----

## Feature description

There are additional update features available to plugins and themes related to updating (with WP 5.5). We can point to a file now somewhere and have that be updated. 

That way, once the plugin/theme are in .org, it will allow for smoother flows with updating to the latest versions. 

See #460 #461

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. A user is able to receive auto-updates
2. A user is able to opt-out of auto-updates

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jwold"><img src="https://avatars.githubusercontent.com/u/3411173?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwold](https://github.com/jwold)**
_Friday Aug 21, 2020 at 16:22 GMT_

----

@ravichdev can you add an implementation brief to this one?

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Friday Dec 04, 2020 at 16:45 GMT_

----

see the above comment for the next steps.

**Comment by csossi** [comment]
Verified in QA
