### ISSUE TITLE
[DISCOVERY] Pattern Research

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#82]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Thursday Mar 11, 2021 at 22:27 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/563_

----

## Feature description

Research plugins for inspiration on patterns:
1. https://atomicblocks.com/
2. https://ultimateblocks.com/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Report back on patterns to consider to build

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
no longer needed
