### ISSUE TITLE
Theme: Explore - Add option to exclude padding above page title

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#83]
<a href="https://github.com/ravichdev"><img src="https://avatars.githubusercontent.com/u/26096061?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ravichdev](https://github.com/ravichdev)**
_Thursday Mar 25, 2021 at 18:40 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/570_

----

## Feature description

Explore - add an option to exclude padding above page title for pages, this could be set at a page level.

See:
https://wordpress.org/support/topic/white-space-on-top/
https://wordpress.org/support/topic/how-can-i-recreate-the-theme-screenshot-layout/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Add a toggle option at the page level, under page attributes to hide the title
2. By default the title should be shown

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
@rodydavis What are your thoughts on adding an option at the page level to hide the title?

**Comment by csossi** [comment]
Verified in QA
