### ISSUE TITLE
[PLUGIN] Keep Google Fonts Up to date 

### ISSUE THREAD

**Issue by ravichdev** [material-components/material-design-for-wordpress#9]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 14:15 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/460_

----

## Feature description

I want access to the latest Google Fonts.

Resources: https://developers.google.com/fonts/docs/developer_api
Related to #354
This ticket was split from #383 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Fonts should be auto-updated (interval or auto-detection on when an update is available)
2. Add an option to opt-out of auto-updates 
3. A plugin update is not required to receive Font updates
4. Performance should be kept in mind (e.g. use caching, not cron job, look at how PWAs work) (nice to have)
## Implementation brief

* Updates should happen when the Selector comes into focus in the Customizer
* An update constitutes checking a transient in the database. If an install has an object cache, core behavior stores transients as cached items and reduces reads on MySQL.
* A transient should have a 24h expiry to avoid overloading the Fonts API
* If a transient exists, bail and let existing behavior read from local stored JSON file in `assets/fonts/google-fonts.json`.
* If transient does not exist, or is expired, request new list from the Google Fonts API. `https://www.googleapis.com/webfonts/v1/webfonts?key={key}&fields=items(category,variants,family)`
* Because the JSON payload provided by Google does not match the format currently used, perform a simple transformation and write to the existing file. This is a small transform that moves the family property from the payload to the key. This will allow existing functionality to continue to work with no further compatibility layer.
* Write the transformed JSON to `assets/fonts/google-fonts.json` for future use and npm.

**Existing Format**
```
{
	{
      "family": "Roboto",
      "variants": [
        "100",
        "100italic",
        "300",
        "300italic",
        "regular",
        "italic",
        "500",
        "500italic",
        "700",
        "700italic",
        "900",
        "900italic"
      ],
      "category": "sans-serif"
    }
}
```

**Google JSON format**
```
{
    "Roboto": {
        "variants": [
            "100",
            "100italic",
            "300",
            "300italic",
            "regular",
            "italic",
            "500",
            "500italic",
            "700",
            "700italic",
            "900",
            "900italic"
        ],
        "category": "sans-serif"
    }
}
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 17:11 GMT_

----

After the IB is written, please assign to Rody to review

**Comment by ravichdev** [comment]
<a href="https://github.com/jauyong"><img src="https://avatars.githubusercontent.com/u/5874851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jauyong](https://github.com/jauyong)**
_Tuesday Dec 08, 2020 at 16:30 GMT_

----

Assigning myself until Aaron is added to the project

**Comment by ravichdev** [comment]
<a href="https://github.com/technosailor"><img src="https://avatars.githubusercontent.com/u/725303?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [technosailor](https://github.com/technosailor)**
_Tuesday Dec 15, 2020 at 16:14 GMT_

----

Hi @rodydavis-

I failed to assign this to you yesterday. So now I have.

Please review the updated implementation brief. 

Thanks!

**Comment by ravichdev** [comment]
<a href="https://github.com/rodydavis"><img src="https://avatars.githubusercontent.com/u/31253215?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodydavis](https://github.com/rodydavis)**
_Thursday Dec 17, 2020 at 17:06 GMT_

----

Approved! Looks great to me. Similar to #461

**Comment by csossi** [comment]
Verified in QA
