### ISSUE TITLE
[Pattern] Features (list)

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#94]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115751165-ea6dfb00-a366-11eb-913d-e68ae8a9f17c.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA

Assuming here that this pattern consists of Heading, Paragraph, and 3 columns of List items
