### ISSUE TITLE
[Pattern] Latest Posts

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#95]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115756326-16d84600-a36c-11eb-8cfb-188ebf1377a6.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ravichdev** [comment]
@dawidmlynarz @jauyong @PatelUtkarsh The block pattern title says "Latest Posts" but looks like it's using Cards Collection block with custom cards, wouldn't that confuse users as we also have a "Latest Posts" block ? Should we use that block instead of Cards Collection ?

**Comment by PatelUtkarsh** [comment]
Yes, it seems it is using a curated card collection block. We should either: 
1. Use the latest posts blocks. OR
1. Change title and use curated collection block.

**Comment by csossi** [comment]
Verified in QA
