### ISSUE TITLE
[Pattern] Pricing

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#99]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

![image](https://user-images.githubusercontent.com/5874851/115757524-746c9280-a36c-11eb-9f14-4b13dfb48865.png)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
@jauyong Gutenberg currently doesn't support border for column blocks. (There is a feature request for same). This pattern will look like following, Thoughts? 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/5015489/117454795-265ab000-af64-11eb-899d-e51b34e06727.png">

**Comment by csossi** [comment]
Verified in QA

**Comment by csossi** [comment]
Assuming this should default to "Buy Now"
![image](https://user-images.githubusercontent.com/16945664/119342008-77f08380-bc62-11eb-98a0-bb6e0c6ee744.png)

**Comment by csossi** [comment]
Verified in QA
